import type { CaseData, GameState, SaveData } from '../engine/types';
import { availableOptions, currentScene, pendingConfrontation, matches } from '../engine/engine';
import { icon, escapeHtml as h } from './icons';
import { roomArt, waveform } from './art';
import { header } from './home';
export function gameView(save: SaveData, data: CaseData): string {
  const game = save.game!;
  const scene = currentScene(game, data);
  const sceneText = scene.variants?.find(v => matches(game, v.when))?.text ?? scene.text;
  const confrontation = pendingConfrontation(game);
  const investigator = data.characters.find(c => c.id === data.investigator)!;
  const speaker = confrontation ? investigator.name : scene.speaker ?? investigator.name;
  const mood = game.tension > 65 ? 'El silencio pesa.' : game.suspicion > 45 ? 'Cada palabra se examina.' : 'El grabador sigue en marcha.';
  return `${header(save, true)}<main class="game-shell"><div class="game-breadcrumb"><button class="text-button" data-action="home">${icon('back')} Menú</button><span>CASO ${data.number}<i>/</i>${h(data.title)}</span><span class="save-status">${icon('check')} Guardado local</span></div><div class="investigation-layout"><div class="interrogation"><section class="stage ${scene.kind === 'memory' ? 'memory-stage' : ''}" aria-label="Sala de interrogatorios">${roomArt(data.number)}<div class="stage-top"><span>${scene.kind === 'memory' ? 'FRAGMENTO DE MEMORIA' : 'DECLARACIÓN EN CURSO'}</span><span class="record-label"><span class="live-dot"></span> REC <span>${h(scene.time)}</span></span></div><div class="stage-bottom"><span>${h(scene.chapter)}</span><span>${h(mood)}</span></div></section>
    <section class="dialogue ${confrontation ? 'confrontation' : ''}" aria-labelledby="speaker"><div class="speaker-line"><span class="speaker-marker"></span><h1 id="speaker">${h(speaker)}</h1><span>${confrontation ? 'CONTRADICCIÓN DETECTADA' : scene.kind === 'memory' ? 'RECONSTRUCCIÓN' : 'INSPECTOR' + (investigator.name.startsWith('Inés') ? 'A' : '')}</span><button class="text-button reveal-button" data-action="reveal">Mostrar texto ${icon('arrow')}</button></div>
    ${game.lastReaction ? `<p class="reaction">${h(game.lastReaction)}</p>` : ''}
    ${confrontation ? confrontationBody(game, data) : `<div class="dialogue-text" data-progressive>${h(sceneText).replace(/\n/g, '<br>')}</div>${scene.aside ? `<p class="aside">${h(scene.aside)}</p>` : ''}<div class="answers">${availableOptions(game, data).map((o, i) => `<button class="answer" data-action="answer" data-id="${o.id}"><span class="answer-number">${i + 1}</span><span>${h(o.text)}${o.hint ? `<small>${h(o.hint)}</small>` : ''}</span>${icon('arrow')}</button>`).join('')}</div>${scene.input ? `<form id="free-response" class="free-response"><label for="declaration">Tu declaración</label><p>${h(scene.input.prompt)} Lugares reconocidos: ${scene.input.categories.filter(c => !['unknown', 'other', 'silence'].includes(c.id)).map(c => h(c.label.replace('Estaba ', '').replace('.', ''))).join(', ')}.</p><div class="input-row"><input id="declaration" name="declaration" maxlength="400" placeholder="Escribí lo que recordás…" autocomplete="off" required aria-describedby="input-help"><button class="button secondary" type="submit">Revisar ${icon('arrow')}</button></div><span id="input-help">Tu frase se registra solo después de confirmar su interpretación.</span><div id="interpretation"></div></form>` : ''}`}
    ${save.settings.showStats ? `<div class="mobile-stats"><span>Sospecha: ${game.suspicion}</span><span>Tensión: ${game.tension}</span></div>` : ""}<div class="dialogue-footer"><span>${icon('quote')} ${game.declarations.length} declaraciones registradas</span><button class="text-button" data-action="journal">Consultar expediente ${icon('folder')}</button></div></section></div>
    <aside class="case-sidebar"><div class="sidebar-heading"><p class="eyebrow">EXPEDIENTE ${data.number}</p><h2>${h(data.title)}</h2><span class="tag">${game.endingId ? 'RESUELTO' : 'INVESTIGACIÓN ABIERTA'}</span></div><div class="tape-widget"><span class="eyebrow">GRABADORA · CANAL 01</span>${waveform()}<span class="tape-time">${h(scene.time)}<small>DECLARACIÓN ${String(game.choices.length + 1).padStart(3, '0')}</small></span></div><div class="sidebar-section"><div class="subheading"><h3>Sobre la mesa</h3><span>${String(game.discoveredEvidence.length).padStart(2, '0')}</span></div>${game.discoveredEvidence.slice(-4).reverse().map(id => { const e = data.evidence.find(e => e.id === id)!; return `<button class="evidence-mini" data-action="evidence" data-id="${id}"><span class="evidence-icon">${icon(e.kind === 'audio' ? 'sound' : e.kind === 'photo' ? 'eye' : 'folder')}</span><span>${h(e.title)}<small>${h(e.source)}</small></span>${icon('arrow')}</button>`; }).join('')}<button class="button secondary full-width" data-action="journal">${icon('folder')} Abrir expediente</button></div><div class="sidebar-note"><span class="eyebrow">NOTA PARA VOS</span><p>Una contradicción no prueba culpabilidad. Todavía podés explicar, rectificar o guardar silencio.</p></div>${save.settings.showStats ? `<div class="stats"><span>Sospecha <b>${game.suspicion}</b></span><meter min="0" max="100" value="${game.suspicion}"></meter><span>Tensión <b>${game.tension}</b></span><meter min="0" max="100" value="${game.tension}"></meter></div>` : ''}</aside></div></main>`;
}
function confrontationBody(game: GameState, data: CaseData): string {
  const c = pendingConfrontation(game)!;
  return `<div class="conflict-label">${icon('warning')} HAY ALGO QUE NO ENCAJA</div><p class="dialogue-text">${h(c.description)}</p><div class="quoted-statements">${c.declarationIds.map(id => { const d = game.declarations.find(d => d.id === id)!; return `<blockquote>«${h(d.original)}»<cite>Tu declaración · ${h(d.narrativeTime)}</cite></blockquote>`; }).join('')}${c.evidenceIds.map(id => { const e = data.evidence.find(e => e.id === id)!; return `<button class="conflict-proof" data-action="evidence" data-id="${id}">${icon('folder')} ${h(e.title)} · Examinar ${icon('arrow')}</button>`; }).join('')}</div><div class="answers"><button class="answer" data-action="resolve" data-id="rectify"><span class="answer-number">1</span><span>Quiero rectificar mi declaración.</span>${icon('arrow')}</button><button class="answer" data-action="resolve" data-id="explain"><span class="answer-number">2</span><span>Mi recuerdo era incompleto. Necesito explicarlo.</span>${icon('arrow')}</button><button class="answer" data-action="resolve" data-id="challenge"><span class="answer-number">3</span><span>${c.evidenceIds.length ? 'Quiero verificar de dónde salió esa prueba.' : 'Quiero dejar constancia de mi desacuerdo.'}</span>${icon('arrow')}</button><button class="answer" data-action="resolve" data-id="silence"><span class="answer-number">4</span><span>Por ahora, prefiero no responder.</span>${icon('arrow')}</button></div>`;
}
export function endingView(save: SaveData, data: CaseData): string {
  const game = save.game!; const ending = data.endings.find(e => e.id === game.endingId)!;
  return `${header(save)}<main class="ending-page"><div class="ending-art">${roomArt(data.number)}</div><div class="ending-content"><p class="eyebrow">CASO ${data.number} · ${h(data.title)}</p><span class="ending-stamp">DECLARACIÓN CERRADA</span><h1>${h(ending.title)}</h1><p class="eyebrow ending-subtitle">${h(ending.subtitle)}</p><p class="ending-story">${h(ending.text)}</p><div class="ending-consequence"><p class="eyebrow">EL PESO DE TUS DECISIONES</p><p>${h(ending.consequence)}</p></div>${ending.reveals.length ? `<details><summary>Lo que pudiste reconstruir</summary>${ending.reveals.map(r => `<p>${h(r)}</p>`).join('')}</details>` : ''}<div class="ending-stats"><span><b>${game.declarations.length}</b> Declaraciones</span><span><b>${game.discoveredEvidence.length}</b> Pruebas</span><span><b>${save.progress.endings[data.id]?.length ?? 1}/4</b> Finales descubiertos</span></div><div class="ending-actions"><button class="button primary" data-action="home">Volver a los casos ${icon('arrow')}</button><button class="button secondary" data-action="restart">Repetir este caso</button><button class="text-button" data-action="journal">Revisar mi declaración</button></div><p class="aside">Cada desenlace, incluso uno desfavorable, abre el siguiente expediente.</p></div></main>`;
}

