import type { CaseData, SaveData } from '../engine/types';
import { icon, escapeHtml as h } from './icons';
import { caseArt, roomArt } from './art';
export function header(save: SaveData, inGame = false): string {
  return `<header class="topbar"><button class="brand" data-action="home" aria-label="Volver al inicio"><span class="brand-symbol">¿?</span><span>ESTÁS SEGURO<span class="brand-small">ARCHIVO DE INVESTIGACIÓN</span></span></button><nav aria-label="Navegación principal">${inGame ? `<button class="nav-button" data-action="journal" aria-label="Expediente">${icon('folder')}<span>Expediente</span></button>` : `<button class="nav-button" data-action="cases"><span>Los casos</span></button><button class="nav-button" data-action="archive" aria-label="Archivo">${icon('folder')}<span>Archivo</span></button>`}<button class="nav-button" data-action="achievements" aria-label="Logros">${icon('trophy')}<span>Logros</span></button><span class="nav-divider"></span><button class="icon-button" data-action="audio" aria-label="${save.settings.audio ? 'Silenciar audio' : 'Activar audio'}" title="${save.settings.audio ? 'Silenciar audio' : 'Activar audio'}">${icon(save.settings.audio ? 'sound' : 'mute')}</button><button class="icon-button" data-action="settings" aria-label="Opciones" title="Opciones">${icon('settings')}</button></nav></header>`;
}
export function home(save: SaveData, allCases: CaseData[]): string {
  const continueGame = save.game && !save.game.endingId;
  return `${header(save)}<main class="home">
    <section class="hero" aria-labelledby="game-title"><div class="hero-art">${roomArt()}<div class="art-caption"><span class="live-dot"></span> SALA DE INTERROGATORIOS <span>07:04 AM</span></div></div>
    <div class="hero-copy"><p class="eyebrow"><span class="short-line"></span> UN JUEGO DE MISTERIO PSICOLÓGICO</p><h1 id="game-title">¿Estás<br><em>seguro?</em><span class="title-caption">EL JUEGO</span></h1><p class="hero-description">La verdad es una versión.<br>La tuya puede cambiarlo todo.</p><p class="hero-detail">Tres casos. Un interrogatorio.<br>Y alguien que recuerda cada palabra.</p><div class="hero-actions"><button class="button primary" data-action="${continueGame ? 'continue' : 'new'}">${icon('play')} ${continueGame ? 'Continuar partida' : 'Entrar a la sala'} ${icon('arrow')}</button>${continueGame ? '<button class="text-button" data-action="new">Nueva partida</button>' : ''}</div><div class="hero-footnote">${icon('save')} Guardado automático <span>·</span> Sin conexión <span>·</span> Un jugador</div></div></section>
    <section class="case-section" id="cases" aria-labelledby="case-heading"><div class="section-heading"><div><p class="eyebrow">NO TODOS LOS SILENCIOS SON IGUALES</p><h2 id="case-heading">Elegí tu caso<span class="muted-count"> / 03</span></h2></div><p>Lo que digas deja una huella.</p></div><div class="case-grid">${allCases.map(data => caseCard(data, save)).join('')}</div></section>
    <section class="pillars"><div>${icon('quote')}<p><strong>Tus palabras permanecen.</strong><span>Cada declaración puede volver en tu contra.</span></p></div><div>${icon('eye')}<p><strong>Nada es tan evidente.</strong><span>Examiná pruebas. Reconstruí lo que pasó.</span></p></div><div>${icon('fingerprint')}<p><strong>Una verdad. Muchos finales.</strong><span>Una decisión distinta abre otra historia.</span></p></div></section>
  </main><footer><span>¿ESTÁS SEGURO? <span class="footer-dot">·</span> EL JUEGO</span><span>Ficción criminal · Terror psicológico</span><button class="text-button" data-action="credits">Créditos ${icon('arrow')}</button></footer>`;
}
function caseCard(data: CaseData, save: SaveData): string {
  const unlocked = save.progress.unlocked.includes(data.id);
  const endings = save.progress.endings[data.id]?.length ?? 0;
  const active = save.game?.caseId === data.id && !save.game.endingId;
  return `<button class="case-card ${unlocked ? '' : 'locked'}" data-action="case" data-id="${data.id}" aria-label="${h(data.title)}${unlocked ? '' : ', bloqueado'}"><div class="card-picture">${caseArt(data.number)}<span class="case-number">CASO ${data.number}</span><span class="case-badge ${active ? 'in-progress' : ''}">${active ? 'EN CURSO' : endings ? `${endings}/${data.endings.length} FINALES` : unlocked ? 'DISPONIBLE' : `${icon('lock')} BLOQUEADO`}</span></div><div class="card-copy"><p class="eyebrow">${data.genre}</p><h3>${h(data.title)}</h3><p>${h(data.description)}</p><div class="card-bottom"><span>${icon('clock')} ${data.duration}</span><span>${unlocked ? active ? 'Continuar' : 'Abrir expediente' : `Completá el caso ${String(Number(data.number) - 1).padStart(2, '0')}`} ${icon(unlocked ? 'arrow' : 'lock')}</span></div></div></button>`;
}
