import type { CaseData, GameState, SaveData } from '../engine/types';
import { icon, escapeHtml as h } from './icons';
import { caseArt, waveform, evidenceArt } from './art';
import { achievements, caseCompletion } from '../achievements';
export function settingsPanel(save: SaveData, warning?: string): string {
  const s = save.settings;
  return `<p class="modal-intro">La sala se adapta a vos. Las opciones se guardan en este navegador.</p>${warning ? `<p class="notice">${h(warning)}</p>` : ''}<div class="settings-list"><label class="setting"><span>Ambiente y música dinámica<small>Música atmosférica que cambia entre el menú, los casos, los logros y los desenlaces.</small></span><input type="checkbox" data-setting="audio" ${s.audio ? 'checked' : ''}></label><label class="setting"><span>Volumen<small>El juego también funciona en silencio.</small></span><input aria-label="Volumen" type="range" min="0" max="100" value="${s.volume}" data-setting="volume"></label><label class="setting"><span>Reducir movimiento<small>Desactiva las animaciones del ambiente.</small></span><input type="checkbox" data-setting="reducedMotion" ${s.reducedMotion ? 'checked' : ''}></label><label class="setting"><span>Texto instantáneo<small>Mostrá los diálogos completos de inmediato.</small></span><input type="checkbox" data-setting="instantText" ${s.instantText ? 'checked' : ''}></label><label class="setting"><span>Indicadores narrativos<small>Mostrá sospecha y tensión en la sala.</small></span><input type="checkbox" data-setting="showStats" ${s.showStats ? 'checked' : ''}></label><label class="setting"><span>Tamaño del texto</span><select data-setting="textSize" aria-label="Tamaño del texto"><option value="normal" ${s.textSize === 'normal' ? 'selected' : ''}>Normal</option><option value="large" ${s.textSize === 'large' ? 'selected' : ''}>Grande</option></select></label></div><div class="settings-help"><p>${icon('clock')} Tomate tu tiempo. No hay respuestas cronometradas.</p><p>Teclado: 1–9 para responder, E para el expediente, Escape para cerrar ventanas. Tab recorre todos los controles.</p></div><div class="settings-actions"><button class="button secondary" data-action="export">${icon('save')} Exportar guardado</button><button class="text-button danger" data-action="reset">Borrar todos los datos</button></div>`;
}
export function journalPanel(game: GameState, data: CaseData, tab = 'evidence'): string {
  return `<p class="eyebrow">${h(data.title)} · TU EXPEDIENTE</p><div class="tabs" role="tablist" aria-label="Secciones del expediente">${[['evidence', 'Pruebas'], ['statements', 'Declaraciones'], ['conflicts', 'Contradicciones'], ['memories', 'Recuerdos']].map(([id, label]) => `<button role="tab" aria-selected="${tab === id}" class="${tab === id ? 'active' : ''}" data-action="journal-tab" data-id="${id}">${label}</button>`).join('')}</div><section class="journal-content" role="tabpanel">${tab === 'evidence' ? `<div class="evidence-grid">${game.discoveredEvidence.map(id => { const e = data.evidence.find(e => e.id === id)!; return `<button class="evidence-tile" data-action="evidence" data-id="${id}"><span class="evidence-icon">${icon(e.kind === 'audio' ? 'sound' : e.kind === 'photo' ? 'eye' : 'folder')}</span><strong>${h(e.title)}</strong><span>${h(e.description)}</span><small>${h(e.time)} · ${e.reliability === 'disputed' ? 'Fiabilidad discutida' : 'Fuente verificada'}${game.investigatorEvidence.includes(id) ? ' · Conocida por el investigador' : ' · Solo vos'}</small></button>`; }).join('')}</div>` : tab === 'statements' ? game.declarations.length ? game.declarations.map(d => `<article class="statement"><span class="eyebrow">${h(d.narrativeTime)} · DECLARACIÓN ${String(d.order).padStart(2, '0')}</span><blockquote>«${h(d.original)}»</blockquote><p>${h(data.factLabels[d.fact])}: <strong>${h(data.valueLabels[String(d.value)] ?? ({ unknown: 'no recuerda', silence: 'sin responder', other: 'sin especificar' } as Record<string, string>)[String(d.value)] ?? d.value)}</strong></p><span class="tag">${({ active: 'Registrada', rectified: 'Rectificada · original conservado', uncertain: 'Recuerdo incierto', withheld: 'Silencio' })[d.status]}</span></article>`).join('') : '<p class="empty-state">Todavía no hiciste una declaración.</p>' : tab === 'conflicts' ? game.contradictions.length ? game.contradictions.map(c => `<article class="statement"><span class="tag ${c.type === 'possible' ? '' : 'rust'}">${c.type === 'possible' ? 'Información insuficiente' : c.type === 'evidence' ? 'Diferencia con una prueba' : 'Diferencia entre declaraciones'}</span><p>${h(c.description)}</p><small>${h(c.explanation ?? (c.status === 'insufficient' ? 'No se usará como una contradicción confirmada.' : 'Pendiente de confrontación.'))}</small></article>`).join('') : '<p class="empty-state">Todavía no se detectaron diferencias relevantes.</p>' : `<h3>Lo que recordás</h3>${game.memories.length ? game.memories.map(m => `<p class="memory-note">${h(m)}</p>`).join('') : '<p class="empty-state">Algunos recuerdos vuelven cuando algo los despierta.</p>'}<h3>Personas del caso</h3>${data.characters.map(c => `<article class="character"><span class="character-avatar">${h(c.name.split(' ').map(n => n[0]).join(''))}</span><div><strong>${h(c.name)}</strong><small>${h(c.role)}</small><p>${h(c.description)}</p></div></article>`).join('')}`}</section>`;
}
export function evidencePanel(id: string, game: GameState, data: CaseData): string {
  const e = data.evidence.find(e => e.id === id)!;
  return `<p class="eyebrow">PRUEBA ${h(e.id.toUpperCase())} · ${h(e.time)}</p><div class="evidence-document ${e.kind}">${e.kind === 'audio' ? waveform() : `<div class="document-mark">${icon(e.kind === 'photo' ? 'eye' : 'folder')}<span>ARCHIVO ${data.number}</span></div>`}${e.kind === "photo" ? evidenceArt(e.visual) : ""}<p class="document-title">${h(e.title)}</p><p class="evidence-transcript">${h(e.content)}</p><p class="document-source">FUENTE · ${h(e.source)}</p></div><p class="evidence-description">${h(e.description)}</p><p class="aside">${e.reliability === 'disputed' ? 'Testimonio discutido: una diferencia con tu versión no se considera una contradicción confirmada.' : 'El alcance de esta prueba se limita a lo que aparece en su contenido.'}</p>${e.kind === 'audio' ? '<p class="aside">La transcripción es íntegra. El sonido de cinta es ambiental; no hay voces grabadas.</p><button class="button secondary" data-action="tape">Escuchar ambiente de cinta</button>' : ''}<div class="modal-actions"><button class="button secondary" data-action="journal">${icon('back')} Volver al expediente</button>${!game.endingId ? `<button class="button primary" data-action="present" data-id="${id}">Presentar prueba ${icon('arrow')}</button>` : ''}</div>`;
}
export function archivePanel(save: SaveData, cases: CaseData[]): string {
  return `<p class="modal-intro">Solo se muestran las pruebas y los finales que descubriste. Repetir un caso conserva este archivo.</p>${cases.map(data => `<section class="archive-case"><p class="eyebrow">EXPEDIENTE ${data.number}</p><h3>${h(data.title)}</h3><p>${save.progress.evidence[data.id]?.length ?? 0} pruebas · ${save.progress.scenes[data.id]?.length ?? 0} escenas · ${save.progress.endings[data.id]?.length ?? 0}/${data.endings.length} finales</p>${(save.progress.endings[data.id] ?? []).map(id => { const e = data.endings.find(e => e.id === id)!; return `<details><summary>${h(e.title)}</summary><p>${h(e.text)}</p><p class="aside">${h(e.consequence)}</p></details>`; }).join('')}${(save.progress.evidence[data.id] ?? []).length ? `<details><summary>Pruebas encontradas</summary>${(save.progress.evidence[data.id] ?? []).map(id => { const e = data.evidence.find(e => e.id === id)!; return `<article class="statement"><strong>${h(e.title)}</strong><p class="evidence-transcript">${h(e.content)}</p></article>`; }).join('')}</details>` : '<p class="aside">El expediente aún no tiene hallazgos.</p>'}</section>`).join('')}`;
}
export function achievementsPanel(save: SaveData, cases: CaseData[]): string {
  const all = achievements(save.progress, cases);
  const unlocked = all.filter(item => item.unlocked).length;
  const gameAchievement = all.find(item => item.kind === 'game')!;
  return `<div class="achievement-summary"><span class="achievement-seal">${icon('trophy')}</span><div><p class="eyebrow">PROGRESO GENERAL</p><h3>${unlocked} / ${all.length} logros</h3><p>Los finales cuentan al descubrirlos. Un expediente llega al 100% cuando encontraste todos sus finales y todas sus pruebas.</p><span class="achievement-track">${icon('sound')} MÚSICA · TROFEOS EN PENUMBRA</span></div></div><div class="achievement-game ${gameAchievement.unlocked ? 'unlocked' : ''}"><span>${gameAchievement.unlocked ? icon('check') : icon('lock')}</span><div><strong>${h(gameAchievement.title)}</strong><small>${h(gameAchievement.description)}</small></div><b>${gameAchievement.current}/${gameAchievement.total}</b></div>${cases.map(data => {
    const completion = caseCompletion(save.progress, data);
    const caseItems = all.filter(item => item.caseId === data.id);
    const caseGoal = caseItems.find(item => item.kind === 'case')!;
    return `<section class="achievement-case"><div class="achievement-case-head"><div><p class="eyebrow">EXPEDIENTE ${data.number}</p><h3>${h(data.title)}</h3></div><strong>${completion.percent}%</strong></div><div class="achievement-progress" role="progressbar" aria-label="Progreso de ${h(data.title)}" aria-valuenow="${completion.percent}" aria-valuemin="0" aria-valuemax="100"><i style="width:${completion.percent}%"></i></div><div class="achievement-list">${caseItems.filter(item => item.kind === 'ending').map(item => `<article class="achievement ${item.unlocked ? 'unlocked' : 'locked'}"><span>${item.unlocked ? icon('check') : icon('lock')}</span><div><strong>${h(item.title)}</strong><small>${h(item.description)}</small></div></article>`).join('')}<article class="achievement case-goal ${caseGoal.unlocked ? 'unlocked' : 'locked'}"><span>${caseGoal.unlocked ? icon('trophy') : icon('lock')}</span><div><strong>${h(caseGoal.title)}</strong><small>${h(caseGoal.description)}</small></div><b>${caseGoal.current}/${caseGoal.total}</b></article></div></section>`;
  }).join('')}`;
}
export function casePanel(data: CaseData, unlocked: boolean, active: boolean): string {
  return `<div class="case-preview">${caseArt(data.number, true)}</div><p class="eyebrow">${h(data.genre)} · ${h(data.duration)}</p><p class="modal-intro">${h(data.description)}</p><p>Investigador: <strong>${h(data.characters.find(c => c.id === data.investigator)!.name)}</strong></p><p class="aside">Contenido: desapariciones, muerte y presión psicológica. Sin imágenes gráficas ni sustos repentinos.</p>${unlocked ? `<button class="button primary full-width" data-action="${active ? 'continue' : 'start'}" data-id="${data.id}">${active ? 'Continuar la declaración' : 'Iniciar este caso'} ${icon('arrow')}</button>` : `<p class="notice">${icon('lock')} Completá cualquier final del caso anterior para abrir este expediente.</p>`}`;
}
