import type { CaseData } from '../engine/types';
import { scene, option, say, flag, proof, feel, remember, locationDomain } from './helpers';

export const deadFrequency: CaseData = {
  id: 'frecuencia-muerta', number: '04', title: 'La frecuencia muerta', genre: 'DESAPARICIÓN · NOIR RADIOFÓNICO', duration: '25–35 min', color: '#9b715f',
  description: 'Una voz desaparecida interrumpe la radio a medianoche. Vos reconocés la grabación porque fuiste quien la cortó.',
  protagonist: 'mara', investigator: 'ferrero', initialScene: 'dead-air', initialKnowledge: { voice: 'simon', stop: 'tower' },
  truth: { broadcastLive: false, location: 'studio', voice: 'simon', editedAlarm: true, knewFire: true, metSimon: true, stop: 'tower', threat: 'orbe' },
  factLabels: { broadcastLive: 'si la transmisión fue en directo', location: 'tu ubicación a las 00:17', voice: 'la identidad de la voz', editedAlarm: 'la edición de la llamada del incendio', knewFire: 'lo que sabías del incendio', metSimon: 'tu encuentro con Simón', stop: 'el destino que dejó en la grabación', threat: 'la persona que lo amenazaba' },
  valueLabels: { true: 'sí', false: 'no', studio: 'en el estudio', home: 'en tu casa', street: 'en la calle', simon: 'Simón Leal', orbe: 'Esteban Orbe', unknown: 'sin identificar', tower: 'en la torre de agua' },
  timeline: [
    { time: '12/05/2019 · 00:11', event: 'Una llamada alerta sobre humo en el depósito de Orbe. La radio demora el aviso después de recibir presión del patrocinador.' },
    { time: '12/05/2019 · 00:19', event: 'El incendio destruye el depósito y mata al sereno Hugo Salas. Mara edita la cinta antes de entregarla.' },
    { time: '21/09/2026 · 22:40', event: 'Simón muestra a Mara la llamada original y anuncia que publicará la investigación.' },
    { time: '21/09/2026 · 23:52', event: 'Simón programa una emisión automática y abandona la radio al detectar que lo siguen.' },
    { time: '22/09/2026 · 00:17', event: 'La emisión interrumpe la señal. Parece en directo, pero el servidor reproduce un archivo programado.' },
    { time: '22/09/2026 · 00:41', event: 'El teléfono de emergencia de la antigua torre de agua registra una llamada de tres segundos.' }
  ],
  characters: [
    { id: 'mara', name: 'Mara Véliz', role: 'Vos · operadora de sonido', description: 'Conocés cada zumbido de la emisora y el lugar exacto donde una cinta fue cortada.', personality: 'Metódica, leal hasta que la lealtad se parece demasiado al miedo.', relationship: 'Mentora de Simón y antigua empleada de Orbe.', knowledge: ['Simón conservaba la llamada original.', 'La frase “donde el agua ya no sube” nombra la torre abandonada.'], secret: 'Editaste el horario de una llamada que podía haber acelerado la respuesta al incendio.', participation: 'Encubriste la demora de 2019 y ayudaste a Simón a copiar la cinta antes de que desapareciera.' },
    { id: 'ferrero', name: 'Irene Ferrero', role: 'Fiscal · unidad de personas desaparecidas', description: 'Escucha los silencios con auriculares propios y nunca confunde volumen con certeza.', personality: 'Directa, sobria y cuidadosa con las fuentes técnicas.', relationship: 'Investiga la desaparición de Simón y el incendio reabierto.', knowledge: ['La emisión estaba programada.', 'Orbe intentó entrar al servidor después de medianoche.'], secret: 'Solicitó protección para Simón antes de convocarte.', participation: 'Separa la búsqueda urgente de la responsabilidad por el encubrimiento.' },
    { id: 'simon', name: 'Simón Leal', role: 'Periodista · desaparecido', description: 'Aprendió de vos a no borrar el ruido de fondo antes de escucharlo.', personality: 'Persistente, temerario cuando cree que una historia puede cerrarse.', relationship: 'Fue tu aprendiz durante tres años.', knowledge: ['La cinta de 2019 fue editada.', 'Orbe sabe que recuperó el original.'], secret: 'Programó la transmisión para ganar tiempo y se ocultó en la torre.', participation: 'Reabrió el caso y dejó una ruta verificable hacia su escondite.' },
    { id: 'orbe', name: 'Esteban Orbe', role: 'Director de la radio · patrocinador', description: 'Habla como si cada pregunta fuera una pausa comercial.', personality: 'Controlador, persuasivo y obsesionado con conservar la señal.', relationship: 'Era dueño del depósito incendiado y jefe de Mara.', knowledge: ['La llamada entró ocho minutos antes de lo declarado.'], secret: 'Presionó para demorar el aviso y ordenó editar la copia entregada.', participation: 'Encubrió la cronología del incendio y amenazó a Simón.' },
    { id: 'salas', name: 'Hugo Salas', role: 'Sereno · víctima del incendio', description: 'Su nombre quedó reducido a una línea al final del informe.', personality: 'No consta en el expediente.', relationship: 'Llamó desde el depósito cuando todavía podía salir.', knowledge: ['El fuego comenzó antes de medianoche.'], secret: 'La llamada original registra que la salida norte estaba cerrada.', participation: 'Su aviso fue demorado y después editado.' }
  ],
  evidence: [
    { id: 'air-log', caseId: 'frecuencia-muerta', title: 'Registro de emisión 00:17', kind: 'record', description: 'El servidor distingue una voz en vivo de un archivo programado.', content: '00:17:00 · INSERCIÓN AUTOMÁTICA\nArchivo: FINAL_SI_NO_VUELVO.wav\nProgramado: 23:47 por S. Leal.\nNingún micrófono del estudio estuvo abierto.', source: 'Servidor de continuidad', time: '00:17', facts: { broadcastLive: false }, reliability: 'confirmed', possibleContradictions: ['broadcastLive'], visual: 'wave' },
    { id: 'entry-log', caseId: 'frecuencia-muerta', title: 'La consola abierta', kind: 'record', description: 'Tu credencial quedó activa durante la emisión.', content: 'MARA VÉLIZ · ingreso 23:36\nConsola B activa hasta 00:28.\nLa cámara del acceso muestra que no saliste del edificio en ese intervalo.', source: 'Control de acceso', time: '23:36–00:28', facts: { location: 'studio' }, reliability: 'confirmed', possibleContradictions: ['location'], visual: 'door' },
    { id: 'voiceprint', caseId: 'frecuencia-muerta', title: 'La voz de Simón', kind: 'audio', description: 'Una identificación acústica con límites claros.', content: 'Coincidencia de voz: 97,8% con entrevistas de Simón Leal.\nLa compresión demuestra que el archivo fue exportado antes de emitirse.\nFondo: campana metálica y viento exterior.', source: 'Laboratorio acústico', time: '01:05', facts: { voice: 'simon', broadcastLive: false }, reliability: 'confirmed', possibleContradictions: ['voice', 'broadcastLive'], visual: 'wave' },
    { id: 'raw-alarm', caseId: 'frecuencia-muerta', title: 'La llamada sin cortar', kind: 'audio', description: 'Ocho minutos que faltaban en la copia oficial.', content: '00:11:08 · HUGO SALAS: «Hay humo en el depósito. La salida norte está cerrada».\n00:12:31 · MARA: «Ya aviso».\nLa copia entregada en 2019 comienza a las 00:19:14 y omite ambas frases.', source: 'Cinta de respaldo analógica', time: '2019 · 00:11', facts: { editedAlarm: true, knewFire: true }, reliability: 'confirmed', possibleContradictions: ['editedAlarm', 'knewFire'], visual: 'wave', challenge: { evidence: 'splice-report', reply: 'La pericia del empalme confirma que no es una diferencia de copia: alguien retiró físicamente los primeros ocho minutos.' } },
    { id: 'splice-report', caseId: 'frecuencia-muerta', title: 'Dos cortes bajo la lupa', kind: 'document', description: 'El adhesivo y tu máquina dejan una firma técnica.', content: 'Empalmes a 00:11:06 y 00:19:13.\nÁngulo de corte compatible con la editora M-4 del estudio B.\nRegistro de mantenimiento: operadora asignada, Mara Véliz.', source: 'Pericia de audio', time: '02:12', facts: { editedAlarm: true }, reliability: 'confirmed', possibleContradictions: ['editedAlarm'], visual: 'file' },
    { id: 'simon-message', caseId: 'frecuencia-muerta', title: 'La cita de las 22:40', kind: 'document', description: 'Simón te pidió ayuda antes de desaparecer.', content: 'SIMÓN → MARA\n«Encontré el original. Te veo en el estudio B a las 22:40. Si no querés hablar, al menos decime dónde esconderlo».\nTu respuesta: «Vení solo».', source: 'Mensajería recuperada', time: '22:14', facts: { metSimon: true }, reliability: 'confirmed', possibleContradictions: ['metSimon'], visual: 'phone' },
    { id: 'orbe-contract', caseId: 'frecuencia-muerta', title: 'El precio del silencio', kind: 'document', description: 'Pagos de Orbe vinculados con la edición y la amenaza.', content: 'Transferencia extraordinaria a Mara: 13/05/2019.\nAnexo interno: “corrección de continuidad”.\nMensaje de Orbe a Simón, ayer: «El archivo también puede tragarse a quien lo abre».', source: 'Contabilidad y orden judicial', time: '2019–2026', facts: { threat: 'orbe' }, reliability: 'confirmed', possibleContradictions: ['threat'], visual: 'file' },
    { id: 'tower-call', caseId: 'frecuencia-muerta', title: 'Donde el agua ya no sube', kind: 'record', description: 'La última señal verificable del teléfono de Simón.', content: '00:41:22 · llamada de emergencia de 3 segundos.\nAntena: torre de agua municipal clausurada.\nLa campana de mantenimiento del lugar coincide con el ruido de fondo de la grabación.', source: 'Central telefónica y Obras', time: '00:41', facts: { stop: 'tower' }, reliability: 'confirmed', possibleContradictions: ['stop'], visual: 'map' }
  ],
  rules: [
    { id: 'live-file', kind: 'logical', facts: ['broadcastLive'], when: { all: [{ claim: 'broadcastLive', eq: true }, { evidence: 'air-log', audience: 'investigator' }] }, description: 'Dijiste que Simón habló en directo, pero el servidor registra un archivo programado y ningún micrófono abierto.', rectification: { fact: 'broadcastLive', value: false } },
    { id: 'studio-location', kind: 'temporal', facts: ['location'], when: { all: [{ claim: 'location', eq: 'home' }, { evidence: 'entry-log', audience: 'investigator' }] }, description: 'Ubicaste tu noche en casa, pero tu credencial y la cámara te mantienen dentro del estudio durante toda la emisión.', rectification: { fact: 'location', value: 'studio' } }
  ],
  scenes: [
    scene('dead-air', 'I · La voz después del silencio', '01:26', 'Ferrero reproduce nueve segundos. Simón respira, dice tu nombre y la señal cae.\n«La radio informó que esto ocurrió en directo. Necesito tu versión antes de que la versión de la emisora se vuelva la única».', [
      option('live', 'Simón estaba hablando en directo.', 'voice', [say('broadcastLive', true)]),
      option('file', 'Podía ser una grabación programada.', 'voice', [say('broadcastLive', false)]),
      option('unsure', 'No puedo distinguirlo con nueve segundos.', 'voice', [{ type: 'declare', fact: 'broadcastLive', value: 'unknown', certainty: 'uncertain' }])
    ], { onEnter: [proof('air-log')], aside: 'Una señal puede ser auténtica sin estar ocurriendo ahora.' }),
    scene('voice', 'I · La voz después del silencio', '01:32', 'La respiración está comprimida dos veces. Detrás suena una campana que no pertenece al estudio.\n«¿Reconociste la voz antes de que la radio dijera su nombre?»', [
      option('simon', 'Sí. Era Simón.', 'location', [say('voice', 'simon')]),
      option('orbe', 'Pensé que podía ser Orbe.', 'location', [say('voice', 'orbe')]),
      option('unknown', 'No la identifiqué con certeza.', 'location', [{ type: 'declare', fact: 'voice', value: 'unknown', certainty: 'uncertain' }])
    ], { onEnter: [proof('voiceprint')], kind: 'evidence' }),
    scene('location', 'II · La consola B', '01:39', 'Ferrero apaga el audio. El zumbido de la sala ocupa su lugar.\n«A las 00:17, mientras esa voz salía al aire, ¿dónde estabas vos?»', [option('withhold-location', 'Prefiero no precisar mi ubicación.', 'schedule', [{ type: 'declare', fact: 'location', value: 'silence', certainty: 'withheld' }])], { input: locationDomain('location', 'schedule', [
      { id: 'studio', label: 'En el estudio de la radio.', patterns: ['estudio', 'radio', 'emisora', 'consola'] },
      { id: 'home', label: 'En mi casa.', patterns: ['casa', 'domicilio'] },
      { id: 'street', label: 'En la calle.', patterns: ['calle', 'afuera'] }
    ]) }),
    scene('schedule', 'II · La consola B', '01:46', 'El servidor marca 23:47: Simón dejó el archivo preparado media hora antes de desaparecer. Tu credencial seguía dentro del estudio.\n«La transmisión no nos dice dónde estaba. El fondo quizá sí».', [option('inspect-original', 'Examinar el archivo original.', 'alarm'), option('check-console', 'Revisar primero mi registro de acceso.', 'alarm'), option('accept-scheduled', 'Rectifico: no fue una transmisión en directo.', 'alarm', [say('broadcastLive', false), flag('correctedBroadcast')])], { onEnter: [proof('entry-log')], kind: 'revelation' }),
    scene('alarm', 'III · Los ocho minutos', '01:54', 'El archivo de Simón contiene otra grabación: la llamada del incendio de 2019. La voz del sereno aparece ocho minutos antes que en la copia oficial. También aparece la tuya.\n«Alguien cortó el principio. ¿Fuiste vos?»', [option('admit-edit', 'Sí. Yo hice el corte.', 'meeting', [say('editedAlarm', true), say('knewFire', true), flag('admittedEdit')]), option('deny-edit', 'No edité esa llamada.', 'meeting', [say('editedAlarm', false)]), option('only-orders', 'Orbe dio la orden. Yo obedecí sin escuchar todo.', 'meeting', [say('editedAlarm', true), { type: 'declare', fact: 'knewFire', value: false }, flag('admittedEdit')])], { onEnter: [proof('raw-alarm'), proof('splice-report'), remember('editedAlarm', true, 'Recordás la cinta tensándose bajo la cuchilla de la editora M-4.')], kind: 'memory' }),
    scene('meeting', 'IV · La cita', '02:06', 'Simón te escribió: «Encontré el original». Tu respuesta fue «Vení solo».\nFerrero no completa la frase por vos. «¿Se reunieron a las 22:40?»', [option('met', 'Sí. Me mostró la cinta y pidió ayuda.', 'pressure', [say('metSimon', true)]), option('no-meeting', 'No llegó a esa reunión.', 'pressure', [say('metSimon', false)]), option('partial', 'Lo vi, pero no acepté guardar nada.', 'pressure', [say('metSimon', true), flag('refusedCopy')])], { onEnter: [proof('simon-message')], kind: 'evidence' }),
    scene('pressure', 'IV · La cita', '02:14', 'La orden judicial abre los mensajes de Orbe. El último no habla de audiencia ni de dinero: «El archivo también puede tragarse a quien lo abre».\nSimón guardó una frase en su emisión: «Donde el agua ya no sube».', [option('orbe-threat', 'Orbe lo estaba amenazando.', 'tower', [say('threat', 'orbe')]), option('metaphor', 'Simón usaba metáforas. Puede no ser un lugar.', 'tower'), option('recognize-tower', 'Es la torre municipal clausurada.', 'tower', [say('stop', 'tower'), flag('recognizedTower')])], { onEnter: [proof('orbe-contract'), feel(0, 15)], kind: 'evidence' }),
    scene('tower', 'V · Donde el agua ya no sube', '02:22', 'La central encuentra una llamada de tres segundos desde la torre. En el fondo suena la misma campana oxidada. Hay movimiento junto al acceso y un vehículo registrado a nombre de Orbe.\nFerrero necesita decidir ahora qué equipo enviar y qué hacer con la cinta.', [option('reveal-tower', 'Dar la ubicación y pedir un equipo protegido.', 'decision', [say('stop', 'tower'), flag('revealedTower')]), option('air-first', 'Emitir la llamada original antes de revelar el lugar.', 'decision', [flag('publishFirst')]), option('hide-place', 'No decir dónde está. Darle tiempo para escapar.', 'decision', [flag('protectEscape')]), option('take-blame', 'Confesar la edición y entregar todas las copias.', 'decision', [say('editedAlarm', true), flag('admittedEdit')])], { onEnter: [proof('tower-call')], kind: 'revelation' }),
    scene('decision', 'VI · La señal abierta', '02:29', 'La radio sigue emitiendo música automática. Nadie allí sabe todavía si Simón está escuchando.\n«Puedo proteger la búsqueda, preservar el audio y separar tu responsabilidad de la amenaza», dice Ferrero. «Pero necesito que elijas qué queda asentado».', [
      { ...option('rescue', 'Enviar el equipo a la torre con la prueba contra Orbe.', 'closing', [flag('decision', 'rescue')]), when: { flag: 'revealedTower', eq: true } },
      option('broadcast', 'Hacer pública la llamada completa y sostener mi declaración.', 'closing', [flag('decision', 'broadcast')]),
      option('confess', 'Asumir formalmente la edición de 2019.', 'closing', [say('editedAlarm', true), flag('decision', 'confess')]),
      option('silence', 'No entregar la ubicación ni autorizar la cinta.', 'closing', [flag('decision', 'silence')])
    ], { kind: 'decision' }),
    scene('closing', 'VI · La señal abierta', '02:36', 'Ferrero cierra el archivo de audio sin borrarlo. En la pared, una luz roja indica que otro estudio sigue al aire.\nLa verdad no necesita volumen para quedar grabada.', [option('finish', 'Cerrar la declaración.', '$ending')], { kind: 'revelation' })
  ],
  endings: [
    { id: 'rescate', title: 'Una voz al otro lado', subtitle: 'SIMÓN ENCONTRADO · ORBE BAJO INVESTIGACIÓN', when: { flag: 'decision', eq: 'rescue' }, text: 'El equipo llega a la torre antes que el vehículo de Orbe. Simón abre la puerta con la cinta apretada contra el pecho. No estaba esperando que lo salvaran; estaba esperando saber quién llegaría primero. La llamada de Hugo entra al expediente completa. Cuando volvés a la radio, la luz roja del estudio B sigue encendida. Esta vez no cortás nada.', consequence: 'Uniste la señal, la ubicación y la amenaza en una búsqueda protegida. Tu admisión permitió investigar el encubrimiento sin abandonar a Simón.', reveals: ['Simón programó la emisión para ganar tiempo.', 'Orbe ordenó alterar la llamada del incendio.', 'La torre era un escondite, no el origen de una transmisión en vivo.'] },
    { id: 'aire', title: 'Todo queda al aire', subtitle: 'ARCHIVO PUBLICADO · BÚSQUEDA EXPUESTA', when: { flag: 'decision', eq: 'broadcast' }, text: 'La llamada completa sale por la misma frecuencia que la mutiló siete años antes. En minutos deja de pertenecer a una sola radio. La presión obliga a reabrir el incendio, pero también revela que Simón dejó una pista geográfica. Cuando el equipo llega a la torre, encuentra la puerta abierta y dos juegos de huellas. La verdad circula. Simón, todavía no.', consequence: 'Priorizaste hacer imposible otro encubrimiento. La publicación fortaleció la causa y volvió más peligrosa la búsqueda inmediata.', reveals: ['La llamada de 2019 fue editada.', 'Simón preparó la emisión antes de desaparecer.'] },
    { id: 'confesion', title: 'El corte lleva tu nombre', subtitle: 'RESPONSABILIDAD RECONOCIDA · CINTA PRESERVADA', when: { flag: 'decision', eq: 'confess' }, text: 'Firmás el acta de la edición antes de saber si encontrarán a Simón. Ferrero no convierte tu confesión en una explicación total: conserva los mensajes de Orbe, la cinta y la búsqueda como piezas distintas. A la salida oís tu propia voz en la llamada de 2019. No suena malvada. Suena asustada. Eso no devuelve los ocho minutos.', consequence: 'Asumiste el encubrimiento documentado y entregaste el material. La responsabilidad de Orbe y la localización de Simón siguen abiertas.', reveals: ['Tu edición alteró la cronología oficial del incendio.', 'El silencio fue pagado como una “corrección de continuidad”.'] },
    { id: 'estatica', title: 'Después, estática', subtitle: 'DECLARACIÓN INCOMPLETA · SEÑAL PERDIDA', text: 'La orden protege el servidor, pero no alcanza a proteger a una persona cuya ubicación nadie declaró. Al amanecer, la radio vuelve a su programación habitual. Entre dos canciones queda un segundo de estática. Creés escuchar la campana de la torre. Podría estar ahí. Podría ser el recuerdo de haberla reconocido y callado.', consequence: 'La investigación conservó la emisión y sus metadatos, pero no recibió una decisión capaz de unir la amenaza con la búsqueda.', reveals: [] }
  ]
};
