import type { CaseData } from '../engine/types';
import { scene, option, say, flag, proof, feel, remember, locationDomain } from './helpers';
export const impossibleWitness: CaseData = {
  id: 'testigo-imposible', number: '03', title: 'El testigo imposible', genre: 'TESTIMONIO · THRILLER PSICOLÓGICO', duration: '25–35 min', color: '#729e98',
  description: 'Viste un asesinato. Recordás el rostro. Hay un problema: la víctima murió hace dieciocho años.',
  protagonist: 'leo', investigator: 'mora', initialScene: 'statement', initialKnowledge: { location: 'projection', knowsFather: true },
  truth: { witnessedLive: false, date: 'past', location: 'projection', suspect: 'joaquin', childPresent: true, hidTape: true, knowsFather: true, firstVisit: false },
  factLabels: { witnessedLive: 'si viste el crimen en directo', date: 'la fecha del crimen que viste', location: 'tu ubicación a las 20:40', suspect: 'la identidad del agresor', childPresent: 'la presencia del chico en la sala', hidTape: 'el ocultamiento de la cinta', knowsFather: 'tu relación con Joaquín', firstVisit: 'si era tu primera visita al archivo' },
  valueLabels: { true: 'sí', false: 'no', present: 'anoche', past: 'hace dieciocho años', projection: 'en la cabina de proyección', gallery: 'en la galería', street: 'en la calle', tomas: 'Tomás Arce', joaquin: 'Joaquín Arce' },
  timeline: [
    { time: '17/11/2008 · 20:40', event: 'Joaquín Arce mata a Ana Ledesma en el archivo municipal. Una cámara de seguridad lo registra.' },
    { time: '17/11/2008 · 20:43', event: 'Su hijo Leo, de dieciséis años, esconde la cinta bajo presión de su padre. El caso se archiva como desaparición.' },
    { time: '16/11/2026 · 19:10', event: 'Elisa encuentra el carrete, lo digitaliza sin alterar los fotogramas y cita a Leo al archivo.' },
    { time: '16/11/2026 · 20:40', event: 'Leo ve la reproducción desde la cabina. El código de fecha pertenece al reproductor, no a la grabación.' },
    { time: '16/11/2026 · 21:02', event: 'Leo denuncia a Tomás, medio hermano y parecido a Joaquín, como autor de un crimen ocurrido anoche.' },
    { time: '17/11/2026 · 09:15', event: 'Mora contrasta el carrete original con el parte de la antigua desaparición de Ana.' }
  ],
  characters: [
    { id: 'leo', name: 'Leo Arce', role: 'Vos · archivista', description: 'Volviste al edificio donde tu padre trabajaba. Dijiste que era la primera vez.', personality: 'Preciso al catalogar, evasivo al recordar.', relationship: 'Hijo de Joaquín y medio hermano de Tomás.', knowledge: ['Viste una reproducción desde la cabina.', 'El rostro te resultó familiar.'], secret: 'Escondiste el carrete a los dieciséis años por orden de tu padre.', participation: 'Fuiste testigo del crimen original y después denunciaste a la persona equivocada.' },
    { id: 'mora', name: 'Alicia Mora', role: 'Investigadora · delitos históricos', description: 'Nunca termina tus frases. Te hace escucharlas de nuevo.', personality: 'Empática, cuidadosa con la sugestión y firme con la evidencia.', relationship: 'Recibió tu denuncia y pidió revisar su fecha.', knowledge: ['La mujer del video es Ana.', 'El archivo tenía otra distribución en 2008.'], secret: 'La primera denuncia contra Joaquín desapareció del legajo.', participation: 'Compara fuentes independientes antes de aceptar recuerdos.' },
    { id: 'ana', name: 'Ana Ledesma', role: 'Víctima · empleada del archivo', description: 'En el legajo antiguo figura como ausente, no como fallecida.', personality: 'Persistente; se negó a destruir documentos.', relationship: 'Intentó protegerte de la presión de tu padre.', knowledge: ['Joaquín alteraba títulos de propiedad.'], secret: 'Grabó la discusión para preservar una prueba.', participation: 'Fue asesinada por Joaquín en 2008.' },
    { id: 'joaquin', name: 'Joaquín Arce', role: 'Tu padre · exdirector del archivo', description: 'Su retrato todavía cuelga en el vestíbulo.', personality: 'Autoritario; confunde lealtad con obediencia.', relationship: 'Te ordenó guardar la cinta.', knowledge: ['Leo vio lo que hizo.'], secret: 'Mató a Ana y firmó la orden de cerrar su legajo.', participation: 'Agresor en la grabación original.' },
    { id: 'tomas', name: 'Tomás Arce', role: 'Sospechoso señalado · tu medio hermano', description: 'Tiene la misma forma de caminar que tu padre.', personality: 'Distante de la familia, poco dispuesto a explicarse.', relationship: 'Lo identificaste por un parecido, no por una imagen nítida.', knowledge: ['No estuvo en el archivo anoche.'], secret: 'Investigaba las propiedades heredadas de Joaquín.', participation: 'Fue acusado por tu declaración errónea.' },
    { id: 'elisa', name: 'Elisa Paz', role: 'Restauradora · testigo', description: 'Anota cada empalme y cada etiqueta que encuentra.', personality: 'Rigurosa con los originales; no presume conocer tus recuerdos.', relationship: 'Te invitó a identificar el material.', knowledge: ['El carrete pertenece a 2008.'], secret: 'Encontró tu nombre escrito dentro de la caja.', participation: 'Conservó el original y creó una copia sin modificar fotogramas.' }
  ],
  evidence: [
    { id: 'complaint', caseId: 'testigo-imposible', title: 'Tu denuncia de anoche', kind: 'document', description: 'Firmada antes de que pudieras dormir.', content: '21:02 · LEO ARCE\n«Vi a una mujer caer en el archivo. Reconocí la forma de caminar de Tomás. Fue alrededor de las 20:40».\nLa denuncia no distingue entre ver una imagen y presenciar el hecho en persona.', source: 'Mesa de denuncias', time: '21:02', facts: {}, reliability: 'confirmed', possibleContradictions: [], visual: 'file' },
    { id: 'projection-log', caseId: 'testigo-imposible', title: 'La cabina ocupada', kind: 'record', description: 'El control de sala confirma desde dónde viste la imagen.', content: '20:36 a 20:49 · Cabina de proyección\nUsuario: Leo Arce.\nCámara interna: Leo permanece en la cabina mirando la pantalla. No hay visión directa hacia la sala filmada.', source: 'Control de sala del archivo', time: '20:40', facts: { location: 'projection', witnessedLive: false }, reliability: 'confirmed', possibleContradictions: ['location', 'witnessedLive'], visual: 'projector' },
    { id: 'elisa-note', caseId: 'testigo-imposible', title: 'Notas de restauración', kind: 'testimony', description: 'Elisa diferencia el contenido de la cinta de la fecha del reproductor.', content: '«No le mostré una transmisión. Digitalicé un carrete. El reloj de abajo era el del reproductor. Leo dijo el nombre de Tomás antes de que yo pudiera explicarle la etiqueta».', source: 'Elisa Paz', time: '19:10', facts: { date: 'past' }, reliability: 'disputed', possibleContradictions: ['date'], visual: 'file' },
    { id: 'old-file', caseId: 'testigo-imposible', title: 'Ana Ledesma · legajo 2008', kind: 'document', description: 'La misma cara en una búsqueda de hace dieciocho años.', content: 'DESAPARICIÓN · 17 NOV 2008\nAna Ledesma, 42 años.\nÚltima ubicación: archivo municipal.\nCierre administrativo solicitado por J. Arce.\nEl retrato coincide con la mujer de la grabación.', source: 'Hemeroteca y legajo original', time: '2008', facts: {}, reliability: 'confirmed', possibleContradictions: [], visual: 'portrait' },
    { id: 'master', caseId: 'testigo-imposible', title: 'El carrete original', kind: 'object', description: 'Una fecha física, fuera de la pantalla.', content: 'Etiqueta de laboratorio: 18 NOV 2008.\nEmpalmes y numeración de fábrica continuos.\nEn los fotogramas aparece la escalera demolida en 2011.\nLa pericia sitúa el material en 2008. No es una filmación de anoche.', source: 'Original preservado por Elisa', time: '2008', facts: { date: 'past', witnessedLive: false }, reliability: 'confirmed', possibleContradictions: ['date', 'witnessedLive'], visual: 'reel', challenge: { evidence: 'building', reply: 'El plano municipal confirma que esa escalera dejó de existir en 2011. La fecha no depende de la memoria de Elisa.' } },
    { id: 'building', caseId: 'testigo-imposible', title: 'Una escalera demolida', kind: 'document', description: 'Un elemento de la escena que ya no existe.', content: 'REFORMA DEL ARCHIVO · 2011\nRetiro de escalera este y tabique de sala 4.\nLa grabación muestra ambos elementos intactos.\nEl plano fue archivado por una dependencia distinta.', source: 'Dirección de obras municipales', time: '2011', facts: {}, reliability: 'confirmed', possibleContradictions: [], visual: 'map' },
    { id: 'voice', caseId: 'testigo-imposible', title: 'La voz detrás del vidrio', kind: 'audio', description: 'El canal que no escuchaste anoche.', content: 'ANA: No le pidas eso a un chico.\nJOAQUÍN: Salí de acá, Leo.\n[un golpe; respiración cerca del micrófono]\nLEO, 16 AÑOS: ¿Dónde guardo la caja?\nJOAQUÍN: Donde nadie la encuentre.\nPericia: las voces y el video pertenecen a la misma toma continua.', source: 'Canal secundario del carrete', time: '20:43 · 2008', facts: { childPresent: true, knowsFather: true }, reliability: 'confirmed', possibleContradictions: ['childPresent', 'knowsFather'], visual: 'wave' },
    { id: 'box', caseId: 'testigo-imposible', title: 'La caja con tu letra', kind: 'object', description: 'La tapa tiene una instrucción que reconocés.', content: '«NO ABRIR. LEO».\nCotejo de escritura con tu cuaderno escolar y huellas internas conservadas.\nTu nota de 2008: «La guardé debajo del escenario, como dijo papá».', source: 'Hallazgo bajo el antiguo escenario', time: '2008', facts: { hidTape: true, firstVisit: false }, reliability: 'confirmed', possibleContradictions: ['hidTape', 'firstVisit'], visual: 'box' },
    { id: 'ledger', caseId: 'testigo-imposible', title: 'El nombre al pie', kind: 'document', description: 'La firma que une el crimen con su encubrimiento.', content: 'Joaquín Arce firma el retiro del legajo de Ana y la transferencia de tres inmuebles que ella investigaba.\nUna fotografía institucional de ese día muestra su cicatriz en la mano, visible también en el carrete.\nTomás tenía ocho años en 2008. No puede ser el adulto filmado.', source: 'Libro de resoluciones y registro civil', time: '18/11/2008', facts: { suspect: 'joaquin', knowsFather: true }, reliability: 'confirmed', possibleContradictions: ['suspect', 'knowsFather'], visual: 'file' }
  ],
  rules: [
    { id: 'viewpoint', kind: 'temporal', facts: ['witnessedLive', 'location'], when: { all: [{ claim: 'witnessedLive', eq: true }, { claim: 'location', eq: 'projection' }, { evidence: 'projection-log', audience: 'investigator' }] }, description: 'Afirmaste presenciar el hecho en directo, pero ubicás tu observación en una cabina sin visión hacia la sala. Esa ubicación solo permite ver la proyección.', rectification: { fact: 'witnessedLive', value: false } },
    { id: 'first-visit', kind: 'logical', facts: ['firstVisit', 'childPresent'], when: { all: [{ claim: 'firstVisit', eq: true }, { claim: 'childPresent', eq: true }] }, description: 'Si el chico del carrete eras vos, anoche no pudo ser tu primera visita al archivo. Las dos versiones describen la misma persona en momentos distintos.', rectification: { fact: 'firstVisit', value: false } }
  ],
  scenes: [
    scene('statement', 'I · Lo que viste', '09:18', '«No te voy a pedir que cierres los ojos», dice Mora. «Prefiero que miremos lo que tenemos».\nTu denuncia está abierta. La firma parece de otra persona.\n«Cuando dijiste que viste un asesinato, ¿querías decir que ocurrió delante de vos, en ese momento?»', [
      option('live', 'Sí. Lo presencié anoche, en directo.', 'identity', [say('witnessedLive', true), say('date', 'present')]),
      option('screen', 'Vi una imagen. Supuse que estaba ocurriendo en ese momento.', 'identity', [say('witnessedLive', false), { type: 'declare', fact: 'date', value: 'unknown', certainty: 'uncertain' }]),
      option('uncertain', 'Ya no estoy seguro de qué significa haberlo visto.', 'identity', [{ type: 'declare', fact: 'witnessedLive', value: 'unknown', certainty: 'uncertain' }])
    ], { onEnter: [proof('complaint')], aside: 'Tu certeza y la fecha de una imagen son cosas diferentes.' }),
    scene('identity', 'I · Lo que viste', '09:24', '«Señalaste a Tomás. ¿Lo reconociste o algo te hizo pensar en él?»\nLa pregunta no es amable ni cruel. Solo deja un espacio en el que antes habías puesto una respuesta.', [
      option('tomas', 'Era Tomás. Lo afirmo.', 'location', [say('suspect', 'tomas')]),
      option('similar', 'Se movía como él. No vi bien su cara.', 'location', [{ type: 'declare', fact: 'suspect', value: 'tomas', certainty: 'uncertain' }]),
      option('joaquin', 'Me recordó a mi padre, Joaquín.', 'location', [{ type: 'declare', fact: 'suspect', value: 'joaquin', certainty: 'uncertain' }])
    ]),
    scene('location', 'II · El lugar desde donde mirás', '09:31', 'Mora te acerca el plano del archivo.\n«Ubicate vos, no a la persona de la imagen. A las 20:40, ¿dónde estabas?»', [option('unclear', 'No puedo precisar mi ubicación.', 'projection', [{ type: 'declare', fact: 'location', value: 'unknown', certainty: 'uncertain' }])], { input: locationDomain('location', 'projection', [
      { id: 'projection', label: 'En la cabina de proyección.', patterns: ['cabina', 'proyeccion', 'proyector'] },
      { id: 'gallery', label: 'En la galería del archivo.', patterns: ['galeria', 'sala principal'] },
      { id: 'street', label: 'En la calle.', patterns: ['calle', 'afuera', 'vereda'] }
    ]) }),
    scene('projection', 'II · El lugar desde donde mirás', '09:38', 'El registro muestra catorce minutos dentro de la cabina. Ninguna ventana da a la sala donde cayó la mujer.\n«Viste algo real en una pantalla. Eso no establece cuándo ocurrió. Elisa dice que el carrete era antiguo».', [option('elisa', 'Escuchar la explicación de Elisa.', 'restoration'), option('victim', 'Antes, identificar a la mujer.', 'old-file'), option('first', 'No conocía el edificio. Era mi primera visita.', 'restoration', [say('firstVisit', true)])], { onEnter: [proof('projection-log'), feel(0, 13)], kind: 'evidence' }),
    scene('restoration', 'III · La fecha que no pertenece', '09:45', 'Elisa escribió todo: formato, velocidad, empalmes. No escribió una interpretación de tu cara.\n«El número en pantalla era de mi reproductor», declaró. «No de la cámara que filmó».\nMora deja la nota a un lado. «Podemos comprobarlo sin creerle por fe».', [option('original', 'Examinar el carrete físico.', 'master'), option('victim-file', 'Cruzar el rostro con el legajo antiguo.', 'old-file'), option('hold-date', 'Mantengo que ocurrió anoche.', 'master', [say('date', 'present')])], { onEnter: [proof('elisa-note')], kind: 'evidence' }),
    scene('old-file', 'III · La fecha que no pertenece', '09:52', 'Ana Ledesma. Cuarenta y dos años. Desaparecida en 2008.\nEn el retrato tiene la misma blusa que en la pantalla. En el margen del legajo, una firma conocida autoriza cerrar la búsqueda.\nSentís que ya leíste esta página. Mucho antes de aprender a archivarla.', [option('check-master', 'Buscar una fecha independiente en el original.', 'master'), option('recognize', 'Yo conocía este archivo de chico.', 'master', [say('firstVisit', false)])], { onEnter: [proof('old-file')], kind: 'memory' }),
    scene('master', 'III · La fecha que no pertenece', '10:01', 'La etiqueta del laboratorio es de 2008. Las perforaciones y los empalmes son continuos. Una escalera dentro del plano fue demolida en 2011.\nTres fuentes no comparten un recuerdo. Comparten una fecha.\n«¿Querés corregir el momento del crimen en tu denuncia?»', [
      option('correct-date', 'Sí. Lo que vi pertenece a 2008.', 'child', [say('date', 'past'), flag('correctedDate')]),
      option('challenge-date', 'Pedir el plano de la demolición antes de corregir.', 'building'),
      option('double-down', 'No. Mantengo mi denuncia tal como está.', 'child', [flag('maintainedDate')])
    ], { onEnter: [proof('master'), proof('old-file')], kind: 'revelation' }),
    scene('building', 'III · La fecha que no pertenece', '10:09', 'El plano vino de Obras, no del archivo de Joaquín. La escalera del video ya no existe.\nMora no dice «te lo dije». Marca 2011 con un lápiz y espera.', [option('accept-date', 'Rectificar: el crimen fue antes de la demolición, en 2008.', 'child', [say('date', 'past'), flag('correctedDate')]), option('refuse-date', 'No quiero modificar mi versión.', 'child', [flag('maintainedDate')])], { onEnter: [proof('building')], kind: 'evidence' }),
    scene('child', 'IV · La otra voz', '10:17', 'Hay una segunda respiración en la grabación. No viene del pasillo. Está muy cerca del micrófono.\n«En la sala había un chico», dice Mora. «Antes de escuchar el canal completo, decime si lo recordás».', [option('child-me', 'Ese chico era yo.', 'voice', [say('childPresent', true)]), option('no-child', 'No había ningún chico. Yo no estaba ahí.', 'voice', [say('childPresent', false)]), option('listen', 'Quiero escuchar sin adivinar.', 'voice')]),
    scene('voice', 'IV · La otra voz', '10:23', '«Salí de acá, Leo».\nLa voz de tu padre no tiene la edad que tiene ahora. La tuya tampoco.\nDespués del golpe, el chico pregunta dónde guardar la caja. No necesitás mirar el rostro para reconocer esa manera de pedir permiso.', [option('admit-child', 'Yo estaba ahí. Mi padre me ordenó guardar algo.', 'box', [say('childPresent', true), say('knowsFather', true)]), option('deny-family', 'No conozco al hombre que habla.', 'box', [say('knowsFather', false)]), option('memory', 'Seguir el recuerdo de la caja.', 'memory')], { onEnter: [proof('voice'), remember('childPresent', true, 'La voz joven que pide instrucciones es la tuya. Tu padre te ordena salir de la sala.'), feel(0, 22)], kind: 'memory' }),
    scene('memory', 'IV · La otra voz', '10:29', 'La caja pesa poco. Eso es lo peor del recuerdo: debería pesar más.\nTenés dieciséis años y la sostenés debajo del escenario mientras tu padre cuenta hasta diez. Cuando llega a nueve, la empujás con el pie.\nVolvés a la mesa. Mora no escribió nada durante ese silencio.', [option('admit-hide', 'La escondí. Tenía miedo de él.', 'box', [say('hidTape', true), flag('admittedPast')]), option('deny-hide', 'Yo no escondí esa cinta.', 'box', [say('hidTape', false)])], { onEnter: [remember('hidTape', true, 'Escondiste la caja bajo el escenario bajo presión de tu padre.'), feel(0, 10)], kind: 'memory', speaker: 'Tu recuerdo' }),
    scene('box', 'V · El nombre que falta', '10:38', 'La caja apareció bajo el escenario. Elisa fotografió la tapa antes de tocarla.\nTu letra. Tu nombre. Una nota que dice «como dijo papá».\nMora habla despacio: «Lo que te obligaron a hacer de chico y lo que decidas declarar hoy no son la misma decisión».', [
      option('admit-past', 'Yo la escondí. Quiero reconstruir lo que hizo Joaquín.', 'ledger', [say('hidTape', true), flag('admittedPast')]),
      option('protect-father', 'Corregir la acusación a Tomás, sin hablar de mi padre.', 'decision', [flag('protectFather')]),
      option('denial', 'Todo esto fue preparado para hacerme cambiar la denuncia.', 'ledger', [flag('denial')])
    ], { onEnter: [proof('box')], kind: 'revelation' }),
    scene('ledger', 'V · El nombre que falta', '10:46', 'Tomás tenía ocho años en 2008. El adulto del carrete tiene la cicatriz que tu padre muestra en las fotos de ese año.\nJoaquín firmó el cierre del legajo y recibió los inmuebles que Ana investigaba.\n«El parecido te llevó hasta un nombre. Los documentos nos llevan hasta otro».', [option('name-father', 'Fue Joaquín. Voy a aportar lo que recuerdo y lo que hice.', 'decision', [say('suspect', 'joaquin'), flag('namedFather')]), option('only-exonerate', 'Retiro la identificación de Tomás. No puedo decir más.', 'decision', [flag('withdrawTomas')]), option('insist', 'Sigo sosteniendo que fue Tomás, anoche.', 'decision', [say('suspect', 'tomas'), say('date', 'present'), flag('insisted')])], { onEnter: [proof('ledger')], kind: 'revelation' }),
    scene('decision', 'VI · ¿Estás seguro?', '10:55', 'Mora coloca tu denuncia junto al carrete.\n«Puedo registrar una corrección, una ampliación o tu decisión de no seguir. No voy a completar tus recuerdos por vos».\nLa pregunta de ahora ya no es qué viste. Es qué vas a dejar escrito.', [
      { ...option('full', 'Ampliar: señalar a Joaquín y declarar mi participación en el ocultamiento.', 'closing', [flag('decision', 'full')]), when: { all: [{ flag: 'correctedDate', eq: true }, { flag: 'admittedPast', eq: true }, { flag: 'namedFather', eq: true }, { evidence: 'master', audience: 'investigator' }, { evidence: 'ledger' }] } },
      { ...option('withdraw', 'Retirar la acusación a Tomás y entregar el original.', 'closing', [flag('decision', 'withdraw')]), when: { all: [{ flag: 'correctedDate', eq: true }, { evidence: 'master' }] } },
      option('insist-final', 'Ratificar que Tomás cometió el crimen anoche.', 'closing', [say('suspect', 'tomas'), say('date', 'present'), flag('decision', 'insist')]),
      option('more-date', 'Revisar la fecha antes de firmar.', 'building'),
      option('more-past', 'Hablar de lo que hice con la caja.', 'memory'),
      option('silence', 'No firmar una ampliación. Guardar silencio.', 'closing', [flag('decision', 'silence')])
    ], { kind: 'decision', presentation: { master: { reply: 'El original queda incorporado con su fecha de 2008. Tu corrección temporal queda asentada.', effects: [flag('correctedDate')] }, ledger: { reply: 'Podemos investigar a Joaquín a partir de documentos. Para unirlos a tu experiencia necesitaremos tu declaración.', effects: [flag('ledgerPresented')] } } }),
    scene('closing', 'VI · ¿Estás seguro?', '11:04', 'El grabador se detiene. Por primera vez desde anoche, no confundís su ruido con una respiración.\nMora retira tu denuncia anterior, pero no la rompe.\n«Las correcciones también forman parte del archivo».', [option('finish', 'Entregar la declaración.', '$ending')], { kind: 'revelation' })
  ],
  endings: [
    { id: 'archivo', title: 'El archivo respira', subtitle: 'CRIMEN HISTÓRICO REABIERTO', when: { all: [{ flag: 'decision', eq: 'full' }, { flag: 'admittedPast', eq: true }, { flag: 'namedFather', eq: true }, { flag: 'correctedDate', eq: true }, { evidence: 'ledger' }] }, text: 'El legajo de Ana vuelve a tener una fecha abierta. La grabación, las transferencias y tu declaración llevan la investigación hasta Joaquín. Tu ocultamiento se examina con la edad y la coacción que había entonces, no como una mancha que explique toda tu vida. Visitás el archivo una semana después. La caja está en una estantería numerada. Por primera vez, no sabés quién tiene la llave. Y podés irte sin averiguarlo.', consequence: 'Rectificaste la fecha, reconociste el ocultamiento y uniste tu memoria con documentos independientes. La causa dejó de depender solo de tu voz.', reveals: ['Joaquín mató a Ana en 2008 para ocultar un fraude inmobiliario.', 'Escondiste la cinta siendo menor y bajo su presión.', 'El crimen de anoche era la reproducción de un hecho antiguo.'] },
    { id: 'hermano', title: 'El nombre que retiraste', subtitle: 'TOMÁS EXONERADO DE TU ACUSACIÓN', when: { flag: 'decision', eq: 'withdraw' }, text: 'Tomás deja de figurar como el adulto de una filmación tomada cuando tenía ocho años. La investigación continúa con el original, pero tu declaración no termina de reconstruir quién ordenó esconderlo. Él te manda un mensaje de dos palabras: «Lo leí». No sabés si habla de la corrección o de todo lo que todavía falta. Por ahora, no le contestás.', consequence: 'Corregiste la fecha y retiraste una identificación incompatible con ella. Protegiste a Tomás sin completar tu testimonio sobre Joaquín.', reveals: ['Tomás no podía ser el adulto de la cinta.', 'La imagen pertenecía a 2008.'] },
    { id: 'voz', title: 'Tu voz contra vos', subtitle: 'DENUNCIA RATIFICADA FRENTE A PRUEBAS CONTRARIAS', when: { all: [{ flag: 'decision', eq: 'insist' }, { claim: 'date', eq: 'present' }, { claim: 'suspect', eq: 'tomas' }] }, text: 'Mora conserva las dos declaraciones y todas las pruebas que te mostró entre una y otra. La denuncia contra Tomás pierde sustento. Tu insistencia queda bajo investigación como posible acusación deliberadamente falsa. Nadie te dice que recordar mal sea un delito. Lo que investigarán es la decisión de sostener lo que ya no coincidía con las fuentes que pudiste examinar.', consequence: 'Ratificaste una fecha e identidad después de conocer evidencias incompatibles. La consecuencia surge de esa decisión documentada, no de una memoria imperfecta.', reveals: ['El carrete no muestra un crimen ocurrido anoche.'] },
    { id: 'silencio', title: 'La caja vuelve a cerrarse', subtitle: 'TESTIMONIO INCOMPLETO · INVESTIGACIÓN ABIERTA', text: 'No firmás otra versión. Mora preserva el carrete y envía el legajo a revisión. El caso podrá avanzar sin vos, pero hay una parte de la escena que nadie más puede contar. Al salir, una puerta se cierra detrás tuyo. Es un sonido común. Por primera vez entendés que eso nunca lo volvió inocente.', consequence: 'Guardaste silencio en la ampliación. Las pruebas se conservaron, pero tu experiencia del ocultamiento quedó sin una declaración completa.', reveals: [] }
  ]
};
