import type { CaseData } from '../engine/types';
import { scene, option, say, flag, proof, feel, remember, locationDomain } from './helpers';

export const lastCarriage: CaseData = {
  id: 'ultimo-vagon', number: '05', title: 'El último vagón', genre: 'DESAPARICIÓN · THRILLER FERROVIARIO', duration: '30–40 min', color: '#817b68',
  description: 'Una pasajera subió al último tren y nunca llegó a destino. El convoy hizo una parada que no figura en ningún mapa público.',
  protagonist: 'julian', investigator: 'reyes', initialScene: 'terminal', initialKnowledge: { passenger: 'alma', destination: 'signal-house' },
  truth: { passenger: 'alma', checkedCar: true, location: 'rear', cameraCut: true, stopMade: true, pursuer: 'ledesma', helpedEscape: true, destination: 'signal-house' },
  factLabels: { passenger: 'la identidad de la pasajera', checkedCar: 'si revisaste el último vagón', location: 'tu ubicación a las 23:44', cameraCut: 'el corte de la cámara', stopMade: 'la parada fuera de horario', pursuer: 'la persona que seguía a Alma', helpedEscape: 'tu ayuda para que bajara', destination: 'el lugar donde debía esperar' },
  valueLabels: { alma: 'Alma Quiroga', unknown: 'sin identificar', true: 'sí', false: 'no', rear: 'en el último vagón', cabin: 'en la cabina', platform: 'en el andén', ledesma: 'Ramiro Ledesma', porter: 'el guarda Benítez', 'signal-house': 'en la casilla de señales' },
  timeline: [
    { time: '23:31', event: 'Alma Quiroga valida su boleto y sube al coche 6 con una carpeta de auditoría.' },
    { time: '23:38', event: 'Ledesma entra al tren usando una credencial de seguridad de la concesionaria.' },
    { time: '23:44', event: 'Julián corta la cámara del coche 6 después de escuchar una discusión.' },
    { time: '23:49', event: 'El tren se detiene cuarenta y siete segundos frente a la casilla de señales clausurada.' },
    { time: '23:50', event: 'Julián abre la puerta de servicio y ayuda a Alma a bajar con la carpeta.' },
    { time: '00:12', event: 'El tren llega a cabecera. La cámara vuelve a grabar; el último vagón está vacío.' }
  ],
  characters: [
    { id: 'julian', name: 'Julián Paz', role: 'Vos · guarda del tren nocturno', description: 'Podés reconocer cada curva con los ojos cerrados y cada puerta por el sonido del cierre.', personality: 'Prudente, protector y acostumbrado a resolver emergencias sin testigos.', relationship: 'Alma te pidió ayuda durante el trayecto.', knowledge: ['Hiciste una parada fuera de horario.', 'La casilla tiene un teléfono ferroviario.'], secret: 'Cortaste la cámara y abriste la puerta para que Alma escapara.', participation: 'La ayudaste a bajar, pero ocultaste la parada cuando supiste que faltaba.' },
    { id: 'reyes', name: 'Nadia Reyes', role: 'Investigadora · delitos económicos', description: 'Trae un plano de vías con una estación borrada a lápiz.', personality: 'Paciente con el miedo, inflexible con las acusaciones sin prueba.', relationship: 'Buscaba entrevistar a Alma por la auditoría.', knowledge: ['Ledesma usó una credencial de seguridad.', 'La concesionaria ocultó una parada técnica.'], secret: 'La casilla está bajo vigilancia desde hace veinte minutos.', participation: 'Puede separar el rescate de Alma de la investigación sobre la empresa.' },
    { id: 'alma', name: 'Alma Quiroga', role: 'Auditora · desaparecida', description: 'Subió con una carpeta azul y eligió el asiento más cercano a la puerta de servicio.', personality: 'Cauta, precisa y decidida a conservar documentos fuera de la empresa.', relationship: 'Solo te conocía como guarda del tren.', knowledge: ['Ledesma manipuló contratos de mantenimiento.'], secret: 'Planeaba entregar la carpeta a Reyes esa misma noche.', participation: 'Pidió bajar en la parada técnica para escapar de Ledesma.' },
    { id: 'ledesma', name: 'Ramiro Ledesma', role: 'Jefe de seguridad · concesionaria', description: 'Su credencial abre trenes, talleres y oficinas que dice no visitar.', personality: 'Correcto en público, amenazante cuando puede controlar el registro.', relationship: 'Siguió a Alma desde la terminal.', knowledge: ['Alma copió los contratos.'], secret: 'Ordenó omitir reparaciones y cobró a proveedores inexistentes.', participation: 'Persiguió a Alma e intentó recuperar la carpeta.' },
    { id: 'benitez', name: 'Omar Benítez', role: 'Señalero · testigo', description: 'Trabaja dos kilómetros más adelante y vio detenerse una luz que debía seguir.', personality: 'Rutinario, desconfiado de los horarios corregidos después.', relationship: 'Confirmó la parada, pero no pudo ver quién bajó.', knowledge: ['El tren se detuvo cuarenta y siete segundos.'], secret: 'Prestó a Julián la llave de la casilla meses atrás.', participation: 'Su registro independiente verifica la detención.' }
  ],
  evidence: [
    { id: 'ticket', caseId: 'ultimo-vagon', title: 'Boleto al coche 6', kind: 'record', description: 'Alma atravesó el molinete y subió al tren.', content: 'ALMA QUIROGA · validación 23:31:09\nCoche asignado: 6 · asiento 18.\nCámara de andén: ingreso confirmado con carpeta azul.', source: 'Sistema de pasajeros', time: '23:31', facts: { passenger: 'alma' }, reliability: 'confirmed', possibleContradictions: ['passenger'], visual: 'file' },
    { id: 'camera-gap', caseId: 'ultimo-vagon', title: 'Seis minutos negros', kind: 'record', description: 'La cámara no falló: recibió una orden local.', content: 'CÁMARA C6\n23:44:02 · comando PRIVACIDAD desde panel del guarda.\n23:50:11 · reanudación manual.\nNo se registraron fallas eléctricas en el convoy.', source: 'Registrador del tren', time: '23:44–23:50', facts: { cameraCut: true }, reliability: 'confirmed', possibleContradictions: ['cameraCut'], visual: 'camera' },
    { id: 'position-log', caseId: 'ultimo-vagon', title: 'Tu llave en el último vagón', kind: 'record', description: 'El panel de servicio registra quién lo abrió.', content: '23:43:38 · panel coche 6 desbloqueado.\nLlave electrónica: J. PAZ.\nCierre del panel: 23:50:18.', source: 'Mantenimiento a bordo', time: '23:43', facts: { location: 'rear', checkedCar: true }, reliability: 'confirmed', possibleContradictions: ['location', 'checkedCar'], visual: 'door' },
    { id: 'telemetry', caseId: 'ultimo-vagon', title: 'Cuarenta y siete segundos', kind: 'document', description: 'El tren se detuvo donde no hay estación pública.', content: 'KM 42,8 · velocidad 0 km/h durante 47 s.\nFreno de servicio aplicado desde cabina secundaria.\nNo hubo señal roja ni obstáculo en vía.', source: 'Telemetría independiente', time: '23:49', facts: { stopMade: true }, reliability: 'confirmed', possibleContradictions: ['stopMade'], visual: 'clock' },
    { id: 'door-log', caseId: 'ultimo-vagon', title: 'La puerta que no debía abrir', kind: 'record', description: 'Una apertura de servicio durante la parada.', content: 'COCHE 6 · puerta derecha\nApertura manual: 23:49:19.\nCierre: 23:49:51.\nDesnivel compatible con plataforma técnica de la casilla de señales.', source: 'Control de puertas', time: '23:49', facts: { helpedEscape: true, destination: 'signal-house' }, reliability: 'confirmed', possibleContradictions: ['helpedEscape', 'destination'], visual: 'door' },
    { id: 'recorder', caseId: 'ultimo-vagon', title: 'La discusión del coche 6', kind: 'audio', description: 'El grabador de Alma siguió funcionando dentro de la carpeta.', content: 'LEDESMA: Dame la carpeta.\nALMA: Reyes ya tiene una copia.\nJULIÁN: Aléjese de la puerta.\n[alarma de apertura]\nALMA: La casilla. Dijiste que todavía tiene teléfono.', source: 'Grabador recuperado bajo un asiento', time: '23:48', facts: { pursuer: 'ledesma', helpedEscape: true, destination: 'signal-house' }, reliability: 'confirmed', possibleContradictions: ['pursuer', 'helpedEscape', 'destination'], visual: 'wave', challenge: { evidence: 'credential', reply: 'La credencial de Ledesma y la cámara de terminal lo ubican dentro del tren. La voz no es la única fuente.' } },
    { id: 'credential', caseId: 'ultimo-vagon', title: 'Una credencial fuera de turno', kind: 'photo', description: 'Ledesma entró con acceso de seguridad.', content: '23:38:21 · acceso al coche 5.\nCredencial: R. LEDESMA · fuera de turno.\nLa cámara de conexión lo muestra avanzando hacia el coche 6.', source: 'Control de la concesionaria', time: '23:38', facts: { pursuer: 'ledesma' }, reliability: 'confirmed', possibleContradictions: ['pursuer'], visual: 'portrait' },
    { id: 'signal-call', caseId: 'ultimo-vagon', title: 'La llamada de la casilla', kind: 'record', description: 'Alma alcanzó el teléfono ferroviario después de bajar.', content: '23:54:07 · CASILLA 42 → interno de Delitos Económicos.\nDuración: 12 segundos.\nVoz: «Soy Alma. Tengo la carpeta. Hay alguien afuera».\nLa línea se cortó desde el tablero exterior.', source: 'Central ferroviaria', time: '23:54', facts: { destination: 'signal-house' }, reliability: 'confirmed', possibleContradictions: ['destination'], visual: 'phone' }
  ],
  rules: [
    { id: 'rear-panel', kind: 'logical', facts: ['checkedCar', 'location'], when: { all: [{ claim: 'checkedCar', eq: false }, { claim: 'location', eq: 'rear' }] }, description: 'Negaste haber revisado el coche 6, pero después te ubicás dentro del último vagón en ese mismo intervalo.', rectification: { fact: 'checkedCar', value: true } },
    { id: 'camera-command', kind: 'temporal', facts: ['cameraCut'], when: { all: [{ claim: 'cameraCut', eq: false }, { evidence: 'camera-gap', audience: 'investigator' }] }, description: 'Atribuiste el corte a una falla, pero el registrador conserva un comando manual desde tu panel.', rectification: { fact: 'cameraCut', value: true } }
  ],
  scenes: [
    scene('terminal', 'I · El asiento vacío', '01:08', 'Reyes coloca un boleto sobre la mesa.\n«Alma Quiroga subió al coche 6. El tren llegó, ella no. Empecemos sin interpretar: ¿la viste a bordo?»', [option('saw-alma', 'Sí. La vi en el último vagón.', 'inspection', [say('passenger', 'alma')]), option('did-not-see', 'No vi a esa pasajera.', 'inspection', [{ type: 'declare', fact: 'passenger', value: 'unknown', certainty: 'uncertain' }]), option('name-later', 'Vi a una mujer con una carpeta, pero no sabía su nombre.', 'inspection', [say('passenger', 'alma')])], { onEnter: [proof('ticket')] }),
    scene('inspection', 'I · El asiento vacío', '01:14', 'El protocolo exige recorrer el último coche antes de la terminal. Tu planilla tiene la casilla vacía.\n«¿Lo revisaste o no?»', [option('checked', 'Sí. Entré al coche 6.', 'location', [say('checkedCar', true)]), option('not-checked', 'No. Me quedé en la cabina.', 'location', [say('checkedCar', false)]), option('unsure-check', 'Recuerdo abrir el panel, no el recorrido completo.', 'location', [{ type: 'declare', fact: 'checkedCar', value: 'unknown', certainty: 'uncertain' }])]),
    scene('location', 'II · Seis minutos negros', '01:21', 'La cámara se apaga a las 23:44. No falta energía en ningún otro coche.\n«Ubicate durante esos seis minutos. ¿Dónde estabas?»', [option('withhold-place', 'No puedo precisar dónde estaba.', 'camera', [{ type: 'declare', fact: 'location', value: 'unknown', certainty: 'uncertain' }])], { input: locationDomain('location', 'camera', [
      { id: 'rear', label: 'En el último vagón.', patterns: ['ultimo vagon', 'vagon', 'coche 6', 'atras'] },
      { id: 'cabin', label: 'En la cabina del tren.', patterns: ['cabina', 'adelante'] },
      { id: 'platform', label: 'En el andén.', patterns: ['anden', 'estacion'] }
    ]) }),
    scene('camera', 'II · Seis minutos negros', '01:28', 'El panel del coche 6 conserva dos marcas: tu llave y el comando PRIVACIDAD.\n«No fue un cortocircuito. Alguien con acceso quiso que esos minutos no quedaran filmados».', [option('admit-cut', 'Yo apagué la cámara.', 'stop', [say('cameraCut', true)]), option('deny-cut', 'La cámara falló. No toqué el panel.', 'stop', [say('cameraCut', false)]), option('protect-passenger', 'La apagué porque Alma me pidió que no la grabaran.', 'stop', [say('cameraCut', true), flag('protectedAlma')])], { onEnter: [proof('camera-gap'), proof('position-log')], kind: 'evidence' }),
    scene('stop', 'III · Un punto fuera del mapa', '01:37', 'La telemetría dibuja una línea limpia hasta el kilómetro 42,8. Allí el tren permanece inmóvil cuarenta y siete segundos. No había señal roja.\n«¿Hiciste esa parada?»', [option('made-stop', 'Sí. Detuve el tren.', 'door', [say('stopMade', true)]), option('deny-stop', 'Ese registro está equivocado.', 'door', [say('stopMade', false)]), option('emergency', 'Creí que había una emergencia en el último coche.', 'door', [say('stopMade', true), flag('emergencyClaim')])], { onEnter: [proof('telemetry')], kind: 'revelation' }),
    scene('door', 'III · Un punto fuera del mapa', '01:45', 'Durante la parada se abrió una sola puerta: la de servicio del coche 6. Afuera no había estación, solo la plataforma corta de una casilla clausurada.\nRecordás una carpeta azul golpeando contra el marco.', [option('helped', 'Ayudé a Alma a bajar.', 'recording', [say('helpedEscape', true), say('destination', 'signal-house')]), option('alone-door', 'La puerta se abrió, pero nadie bajó.', 'recording', [say('helpedEscape', false)]), option('memory-door', 'Escuchar lo que quedó grabado antes de responder.', 'recording')], { onEnter: [proof('door-log'), remember('destination', 'signal-house', 'La puerta abrió frente a la casilla de señales. Alma bajó con la carpeta azul.')], kind: 'memory' }),
    scene('recording', 'IV · La persona que avanzaba', '01:54', 'El grabador de Alma estaba debajo del asiento. Ledesma exige la carpeta. Tu voz le ordena alejarse de la puerta.\n«¿A quién estabas protegiendo y de quién?»', [option('name-ledesma', 'Protegía a Alma de Ledesma.', 'signal', [say('pursuer', 'ledesma')]), option('blame-porter', 'El hombre era Benítez, el señalero.', 'signal', [say('pursuer', 'porter')]), option('cannot-name', 'No vi con claridad quién la seguía.', 'signal', [{ type: 'declare', fact: 'pursuer', value: 'unknown', certainty: 'uncertain' }])], { onEnter: [proof('recorder'), proof('credential'), feel(0, 16)], kind: 'evidence' }),
    scene('signal', 'V · La casilla 42', '02:03', 'A las 23:54, Alma llamó desde la casilla: «Tengo la carpeta. Hay alguien afuera». La línea fue cortada desde el tablero exterior.\nReyes ya tiene un equipo cerca, pero una acusación equivocada puede enviarlo hacia la persona incorrecta.', [option('give-location', 'Confirmar la casilla y señalar a Ledesma.', 'decision', [say('destination', 'signal-house'), say('pursuer', 'ledesma'), flag('confirmedRescue')]), option('let-run', 'No revelar la casilla. Alma quería desaparecer.', 'decision', [flag('protectEscape')]), option('accuse-porter', 'Enviar al equipo contra Benítez.', 'decision', [say('pursuer', 'porter'), flag('falseAccusation')]), option('stay-silent', 'No agregar nada a la llamada.', 'decision', [flag('withheldFinal')])], { onEnter: [proof('signal-call')], kind: 'revelation' }),
    scene('decision', 'VI · Cambio de vía', '02:11', 'El equipo espera una dirección. Ledesma todavía tiene acceso a las vías de servicio.\n«Podemos llegar a Alma, preservar la carpeta y registrar por qué rompiste el protocolo», dice Reyes. «Las tres cosas pueden ser ciertas al mismo tiempo».', [
      { ...option('rescue', 'Guiar al equipo a la casilla y entregar los registros.', 'closing', [flag('decision', 'rescue')]), when: { flag: 'confirmedRescue', eq: true } },
      option('protect', 'Sostener el silencio para que Alma escape por su cuenta.', 'closing', [flag('decision', 'protect')]),
      option('accuse', 'Ratificar que Benítez fue quien la siguió.', 'closing', [flag('decision', 'accuse')]),
      option('close', 'Cerrar la declaración sin indicar un destino.', 'closing', [flag('decision', 'silence')])
    ], { kind: 'decision' }),
    scene('closing', 'VI · Cambio de vía', '02:18', 'A lo lejos pasa un tren de carga. La vibración llega a la mesa antes que el sonido.\nReyes guarda el plano. La casilla 42 queda justo sobre el pliegue.', [option('finish', 'Cerrar la declaración.', '$ending')], { kind: 'revelation' })
  ],
  endings: [
    { id: 'senal-verde', title: 'Señal verde', subtitle: 'ALMA ENCONTRADA · DOCUMENTOS PRESERVADOS', when: { flag: 'decision', eq: 'rescue' }, text: 'El equipo encuentra a Alma detrás del tablero, con la carpeta envuelta en su abrigo. Ledesma intenta salir por la vía de mantenimiento y queda registrado por dos cámaras que ya no controla. Cuando el primer tren de la mañana pasa frente a la casilla, vos estás firmando cada ruptura del protocolo. Alma también firma que esas rupturas le dieron cuarenta y siete segundos para seguir viva.', consequence: 'Entregaste una ubicación verificable, identificaste al perseguidor con fuentes independientes y aceptaste tu participación en la fuga.', reveals: ['Alma llevaba pruebas de fraude de la concesionaria.', 'Ledesma la siguió para recuperar la carpeta.', 'La parada y el corte de cámara fueron decisiones deliberadas para ayudarla.'] },
    { id: 'fuera-de-linea', title: 'Fuera de línea', subtitle: 'ALMA ESCAPA · EXPEDIENTE SIN TESTIGO', when: { flag: 'decision', eq: 'protect' }, text: 'La casilla está vacía cuando la vigilancia decide entrar. Falta una bicicleta de mantenimiento y el teléfono cuelga del cable. Dos días después, una copia de la carpeta llega a tres redacciones. Alma no llama a Reyes ni a vos. Ledesma pierde el contrato, pero no desaparece. Cada tren nocturno reduce la velocidad en el kilómetro 42 sin que nadie lo haya ordenado.', consequence: 'Protegiste la fuga y facilitaste la publicación, pero dejaste a Alma fuera de un esquema de protección y sin declarar ante la causa.', reveals: ['Alma planeaba entregar una auditoría sobre la concesionaria.', 'La casilla era un punto de escape elegido durante el trayecto.'] },
    { id: 'via-equivocada', title: 'La vía equivocada', subtitle: 'TESTIGO ACUSADO · PERSEGUIDOR ALERTADO', when: { flag: 'decision', eq: 'accuse' }, text: 'El equipo retiene a Benítez en su puesto. Mientras comparan su voz con la grabación, una camioneta de la concesionaria abandona el acceso a la casilla. La acusación se desarma en menos de una hora; el tiempo que consumió no vuelve. Benítez te mira desde el otro lado del andén cuando lo liberan. No dice que te equivocaste. Pregunta a quién le sirvió.', consequence: 'Ratificaste una identidad incompatible con la credencial y la grabación. La búsqueda perdió tiempo y Ledesma conoció el operativo.', reveals: ['Benítez confirmó la parada, pero no persiguió a Alma.', 'Ledesma estaba dentro del tren fuera de turno.'] },
    { id: 'terminal', title: 'El tren llega vacío', subtitle: 'DECLARACIÓN CERRADA · PARADERO ABIERTO', text: 'La cabecera anuncia la salida del primer servicio. El coche 6 vuelve a circular después de una revisión técnica. El asiento 18 está limpio, el panel reiniciado y la cámara encendida. Nada de eso explica dónde está Alma. Tu declaración conserva una parada, una puerta y un silencio, pero no los convierte en una ruta. El tren llega vacío otra vez. Esta vez todos saben que no es lo mismo que no haber llevado a nadie.', consequence: 'Las pruebas conservan el recorrido y la persecución, pero tu decisión final no permitió llegar a la casilla a tiempo.', reveals: [] }
  ]
};
