import type { CaseData } from '../engine/types';
import { scene, option, say, flag, proof, feel, remember, locationDomain } from './helpers';
export const room309: CaseData = {
  id: 'habitacion-309', number: '02', title: 'Habitación 309', genre: 'HOMICIDIO · TERROR PSICOLÓGICO', duration: '20–30 min', color: '#969278',
  description: 'Una puerta cerrada. Dos testigos. Ambos aseguran haberte visto al mismo tiempo.',
  protagonist: 'nico', investigator: 'vidal', initialScene: 'elevator', initialKnowledge: { entered: true, location: 'boiler' },
  truth: { entered: true, location: 'boiler', upstairs: true, relationship: 'blackmail', force: true, weapon: 'victim', clock: 'fast', aloneAllNight: false },
  factLabels: { entered: 'tu entrada al hotel', location: 'tu ubicación a las 22:51', upstairs: 'tu entrada a la habitación 309', relationship: 'tu relación con Sanz', force: 'el empujón a Sanz', weapon: 'quién tenía el cuchillo', clock: 'la hora de la cámara', aloneAllNight: 'tu aislamiento durante toda la noche' },
  valueLabels: { true: 'sí', false: 'no', boiler: 'en la sala de calderas', hallway: 'en el tercer piso', street: 'fuera del hotel', blackmail: 'me estaba extorsionando', stranger: 'no lo conocía', client: 'era un cliente', victim: 'Sanz tenía el cuchillo', fast: 'la cámara adelantaba trece minutos', correct: 'la cámara marcaba la hora real' },
  timeline: [
    { time: '22:30', event: 'Nico entra por la puerta de servicio para reparar la caldera.' },
    { time: '22:38', event: 'Sube a buscar un fusible. La cámara, adelantada trece minutos, marca 22:51.' },
    { time: '22:51', event: 'Pilar ve a Nico en la caldera; registra el trabajo en una terminal sincronizada.' },
    { time: '22:55', event: 'Sanz exige dinero y cita a Nico en la habitación 309.' },
    { time: '22:58', event: 'Sanz intenta herir a Nico con un cuchillo. Nico lo empuja contra la esquina del escritorio. Sanz muere.' },
    { time: '23:03', event: 'Marta retira el cuchillo para evitar otro escándalo en el hotel. Ofrece a Nico un falso registro de salida.' }
  ],
  characters: [
    { id: 'nico', name: 'Nicolás Ferrer', role: 'Vos · técnico de mantenimiento', description: 'Tenés un corte poco profundo en el antebrazo y una llave que no recordás haber guardado.', personality: 'Reservado; busca causas materiales incluso cuando tiene miedo.', relationship: 'Sanz conocía un accidente laboral que ocultaste.', knowledge: ['Estabas trabajando en la caldera.', 'Sanz te citó arriba.'], secret: 'Lo empujaste al defenderte y huiste sin pedir ayuda.', participation: 'Tu empujón causó la muerte de Sanz.' },
    { id: 'vidal', name: 'Bruno Vidal', role: 'Inspector · homicidios', description: 'Pone dos relojes sobre la mesa. Ninguno funciona.', personality: 'Directo, escéptico de las versiones demasiado ordenadas.', relationship: 'Reconstruye la muerte sin aceptar la cronología del hotel.', knowledge: ['Las cámaras fueron reiniciadas.', 'El cuerpo tiene una lesión por impacto.'], secret: 'Sospecha que el hotel altera registros desde hace meses.', participation: 'Secuestró el registro de puertas antes de que Marta pudiera reemplazarlo.' },
    { id: 'sanz', name: 'Darío Sanz', role: 'Víctima · huésped', description: 'La ficha dice consultor. Nadie en el hotel sabe para quién trabajaba.', personality: 'Amenazante y calculador.', relationship: 'Te extorsionaba por un accidente de trabajo.', knowledge: ['Podía hacerte perder la licencia.'], secret: 'Llevaba un cuchillo y ya había amenazado a Marta.', participation: 'Atacó a Nico y murió por el golpe contra el escritorio.' },
    { id: 'marta', name: 'Marta Acuña', role: 'Recepcionista · testigo', description: 'Usa un saco de mantenimiento cuando sale a fumar.', personality: 'Protectora de la reputación del hotel.', relationship: 'Te ofreció una salida demasiado conveniente.', knowledge: ['Retiró el cuchillo de la 309.', 'Puede imprimir registros falsos.'], secret: 'Ocultó el arma en objetos perdidos.', participation: 'Contaminó la escena y preparó una coartada falsa.' },
    { id: 'pilar', name: 'Pilar Montes', role: 'Encargada de limpieza', description: 'Anota cada reparación porque su turno siempre termina tarde.', personality: 'Práctica, insegura solo cuando otros hablan más fuerte.', relationship: 'Trabajó con vos en la caldera.', knowledge: ['Estabas abajo a las 22:51.'], secret: 'Vio a Marta salir con una bolsa de la 309.', participation: 'Su terminal permite sincronizar la cronología.' }
  ],
  evidence: [
    { id: 'entry', caseId: 'habitacion-309', title: 'Puerta de servicio', kind: 'record', description: 'El sensor registra entrada y rostro, no solo una tarjeta.', content: '22:30:11 · NICOLÁS FERRER\nCredencial M-04. Imagen facial coincidente.\nSalida: no registrada.\nReloj sincronizado con la central de accesos.', source: 'Control de accesos', time: '22:30', facts: { entered: true }, reliability: 'confirmed', possibleContradictions: ['entered'], visual: 'door' },
    { id: 'camera', caseId: 'habitacion-309', title: 'El hombre del pasillo', kind: 'photo', description: 'La imagen es tuya. El horario todavía no está verificado.', content: 'Pantalla: 22:51:04 · TERCER PISO\nNicolás camina hacia el armario de mantenimiento.\nAdvertencia pericial: el equipo se reinició antes de la grabación. La hora impresa no está validada.', source: 'CCTV del hotel', time: '22:51 en pantalla', facts: { location: 'hallway' }, reliability: 'disputed', possibleContradictions: ['location'], visual: 'hall', challenge: { evidence: 'clock-report', reply: 'La pericia confirma un adelanto de trece minutos. Esa imagen corresponde a las 22:38, no a las 22:51.' } },
    { id: 'boiler-log', caseId: 'habitacion-309', title: 'Parte de la caldera', kind: 'record', description: 'Pilar firmó la reparación junto a vos.', content: '22:51 · Presión estabilizada.\nTécnico: Nicolás Ferrer. Testigo: Pilar Montes.\nLa terminal adjunta una imagen del técnico al cerrar el parte. Hora sincronizada por cable con la central.', source: 'Terminal de mantenimiento', time: '22:51', facts: { location: 'boiler' }, reliability: 'confirmed', possibleContradictions: ['location'], visual: 'file' },
    { id: 'clock-report', caseId: 'habitacion-309', title: 'Trece minutos de más', kind: 'document', description: 'La cámara y la terminal no usan el mismo reloj.', content: 'DESFASE MEDIDO: +00:13:00\nCámara 3: 22:51 → hora real: 22:38.\nMétodo: comparar el corte de luz común en CCTV, ascensor y central de accesos.\nLa diferencia no modifica la hora del sensor de la puerta 309.', source: 'Pericia técnica', time: '03:20', facts: { clock: 'fast' }, reliability: 'confirmed', possibleContradictions: ['clock'], visual: 'clock' },
    { id: 'door309', caseId: 'habitacion-309', title: 'El umbral de la 309', kind: 'record', description: 'El registro de puerta está confirmado por una imagen del ascensor.', content: '22:56:43 · Puerta 309 · credencial M-04\nLa cámara del ascensor muestra a Nicolás entrando al corredor.\nNo hay otro ingreso hasta las 23:03, cuando llega Marta.', source: 'Cerradura y ascensor', time: '22:56', facts: { upstairs: true }, reliability: 'confirmed', possibleContradictions: ['upstairs'], visual: 'door' },
    { id: 'message', caseId: 'habitacion-309', title: 'La deuda que no existía', kind: 'document', description: 'El mensaje que te hizo subir.', content: 'SANZ → NICOLÁS · 22:55\n«309. Traé lo acordado o mañana hablo con la empresa. Esta vez no vuelvas con excusas».\nEn los mensajes anteriores aparecen importes crecientes y amenazas de denuncia.', source: 'Tu teléfono', time: '22:55', facts: { relationship: 'blackmail' }, reliability: 'confirmed', possibleContradictions: ['relationship'], visual: 'phone' },
    { id: 'injury', caseId: 'habitacion-309', title: 'La marca en tu brazo', kind: 'photo', description: 'El corte fue documentado antes del interrogatorio.', content: 'Corte reciente y superficial, cara externa del antebrazo. Dirección compatible con maniobra defensiva.\nLa lesión sola no identifica al agresor ni justifica toda la secuencia.', source: 'Examen de ingreso', time: '02:50', facts: {}, reliability: 'confirmed', possibleContradictions: [], visual: 'file' },
    { id: 'knife', caseId: 'habitacion-309', title: 'Objetos perdidos', kind: 'object', description: 'Un cuchillo envuelto en una toalla del hotel.', content: 'Bolsa retirada por Marta de la 309 y entregada a peritos.\nHuellas de Sanz en el mango. Traza de sangre de Nicolás en el filo.\nCoincide con la lesión del antebrazo. No se encontraron huellas de Nicolás en el mango.', source: 'Pilar indicó el armario; peritos retiraron la bolsa', time: '04:12', facts: { weapon: 'victim' }, reliability: 'confirmed', possibleContradictions: ['weapon'], visual: 'knife' },
    { id: 'forensic', caseId: 'habitacion-309', title: 'La esquina del escritorio', kind: 'document', description: 'El impacto pudo producirse durante un forcejeo.', content: 'Lesión fatal por impacto occipital contra la arista del escritorio.\nNo hay heridas de arma blanca en Sanz.\nLa trayectoria es compatible con un empujón frontal, pero no identifica por sí sola a quien empujó.', source: 'Informe preliminar de escena', time: '03:40', facts: {}, reliability: 'confirmed', possibleContradictions: [], visual: 'file' },
    { id: 'alibi', caseId: 'habitacion-309', title: 'Una salida impresa después', kind: 'document', description: 'Marta dejó esta hoja dentro de tus pertenencias.', content: 'SALIDA DE NICOLÁS FERRER · 22:40\nCreación del documento: 23:11.\nNota manuscrita: «Esto nos sirve a los dos. No vuelvas a hablar de la bolsa».\nEl dato contradice el control original de accesos.', source: 'Impresora de recepción', time: '23:11', facts: {}, reliability: 'disputed', possibleContradictions: [], visual: 'file' }
  ],
  rules: [{ id: 'isolation', kind: 'temporal', facts: ['aloneAllNight', 'upstairs'], when: { all: [{ claim: 'aloneAllNight', eq: true }, { claim: 'upstairs', eq: true }] }, description: 'Afirmaste que no saliste de la caldera en toda la noche. Después admitiste entrar a la 309. La segunda afirmación obliga a corregir el alcance de la primera.', rectification: { fact: 'aloneAllNight', value: false } }],
  scenes: [
    scene('elevator', 'I · El tercer piso', '03:07', 'Seguís oyendo el ascensor aunque acá no hay ninguno. Vidal apoya una tarjeta de hotel sobre la mesa.\n«Un hombre murió en la 309. Tu credencial abre esa puerta. Empecemos por algo más sencillo: ¿entraste al hotel anoche?»', [
      option('entered', 'Sí. Fui a reparar la caldera.', 'two-witnesses', [say('entered', true)]),
      option('denied', 'No estuve en ese hotel.', 'two-witnesses', [say('entered', false)]),
      option('card', 'Mi tarjeta pudo usarla otra persona.', 'two-witnesses', [flag('questionedCard')])
    ], { aside: 'Dos relojes pueden contar la misma noche de maneras distintas.' }),
    scene('two-witnesses', 'I · El tercer piso', '03:12', '«La puerta te registró a las 22:30. Pilar te ubica en la caldera a las 22:51. La cámara te pone arriba a la misma hora. Yo no creo en los dobles, Ferrer. Creo en revisar los relojes».\nVidal separa las dos hojas. «Elegí por dónde empezamos».', [option('camera-first', 'Ver la cámara del tercer piso.', 'camera'), option('pilar-first', 'Leer lo que registró Pilar.', 'pilar')], { onEnter: [proof('entry')], kind: 'evidence' }),
    scene('camera', 'II · Dos versiones de un minuto', '03:18', 'La silueta del pasillo es tuya. Se detiene ante el armario de fusibles. Por un momento, jurarías que gira antes que vos.\n«Es una imagen fija», dice Vidal. «No dejes que el cansancio haga el resto».', [option('other-record', 'Compararla con el parte de la caldera.', 'pilar'), option('place-now', 'Declarar dónde estaba a esa hora.', 'location')], { onEnter: [proof('camera'), feel(0, 16)], kind: 'evidence' }),
    scene('pilar', 'II · Dos versiones de un minuto', '03:23', 'Pilar adjuntó una foto a la orden de reparación. Estás al lado del manómetro. El reloj de esa terminal sí está sincronizado.\n«Ella no dice que estuviste abajo toda la noche. Dice que estabas ahí en ese minuto. No lo conviertas en algo más grande».', [option('compare', 'Ver también la imagen del pasillo.', 'camera'), option('locate', 'Precisar dónde estaba a las 22:51.', 'location')], { onEnter: [proof('boiler-log')], kind: 'evidence' }),
    scene('location', 'II · Dos versiones de un minuto', '03:27', '«Sin llenar los huecos: ¿dónde estabas a las 22:51?»\nTe viene una imagen de agua negra dentro del manómetro. Un reflejo detrás de vos. Cuando te das vuelta, no hay nadie.', [option('no-location', 'No puedo precisar un lugar.', 'synchronize', [{ type: 'declare', fact: 'location', value: 'unknown', certainty: 'uncertain' }])], { input: locationDomain('location', 'synchronize', [
      { id: 'boiler', label: 'En la sala de calderas.', patterns: ['(sala de )?calderas?', 'sotano', 'abajo'] },
      { id: 'hallway', label: 'En el tercer piso.', patterns: ['tercer piso', 'pasillo', 'arriba'] },
      { id: 'street', label: 'Fuera del hotel.', patterns: ['fuera del hotel', 'calle', 'afuera'] }
    ]) }),
    scene('synchronize', 'III · El reloj equivocado', '03:32', 'La pericia coloca un corte de luz sobre las tres líneas de tiempo. En la cámara ocurre trece minutos tarde.\n«Las 22:51 de esta imagen son las 22:38 reales. Tu cara no estaba mal. Estaba mal la hora. Ahora reconstruí el orden».', [
      option('align', 'Primero el pasillo, después la caldera.', 'relationship', [say('clock', 'fast'), flag('aligned')]),
      option('ignore-clock', 'Mantengo que la cámara marca la hora correcta.', 'relationship', [say('clock', 'correct')]),
      option('all-night', 'Yo no salí de la caldera durante toda la noche.', 'relationship', [say('aloneAllNight', true)])
    ], { kind: 'revelation', onEnter: [proof('clock-report'), proof('boiler-log'), proof('camera')], presentation: { 'clock-report': { reply: 'Exacto. El pasillo pertenece a las 22:38. El parte de la caldera, a las 22:51. Las dos cosas pueden ser ciertas.', effects: [flag('aligned')] } } }),
    scene('relationship', 'III · El reloj equivocado', '03:38', '«Todavía no hablamos de Sanz. El hotel lo llama cliente. En tu teléfono aparece con otro nombre: No atender. ¿Qué quería de vos?»', [option('blackmail', 'Me estaba extorsionando.', 'message', [say('relationship', 'blackmail')]), option('client', 'Era un cliente más.', 'message', [say('relationship', 'client')]), option('stranger', 'No lo conocía.', 'message', [say('relationship', 'stranger')])]),
    scene('message', 'IV · Detrás de la puerta', '03:44', 'Vidal gira el teléfono hacia vos: «309. Traé lo acordado».\n«La extorsión explica por qué fuiste. No explica lo que pasó después. ¿Entraste a su habitación?»', [option('admit-room', 'Sí. Entré a la 309.', 'door', [say('upstairs', true)]), option('deny-room', 'No crucé esa puerta.', 'door', [say('upstairs', false)]), option('uncertain-room', 'Recuerdo la puerta. No sé qué pasó después.', 'door', [{ type: 'declare', fact: 'upstairs', value: 'unknown', certainty: 'uncertain' }])], { onEnter: [proof('message')], kind: 'evidence' }),
    scene('door', 'IV · Detrás de la puerta', '03:50', 'El sensor y el ascensor coinciden. Esta vez el horario está bien.\nVes tu mano buscando el bolsillo. Sanz dice tu nombre demasiado cerca. Después, el ruido seco. Una parte de vos todavía espera que el ruido vuelva a ocurrir para entenderlo.', [option('remember', 'Quedarme con ese recuerdo.', 'impact'), option('wound', 'Mostrar el corte del antebrazo.', 'injury'), option('reception', 'Marta me dejó algo entre mis cosas.', 'alibi')], { onEnter: [proof('door309'), proof('forensic')], kind: 'memory' }),
    scene('impact', 'IV · Detrás de la puerta', '03:56', 'La mano de Sanz no estaba vacía. Vos retrocediste hasta la puerta, pero la puerta cerraba hacia adentro. Lo empujaste.\nEl escritorio no se movió. Él sí.\n«Un recuerdo no reemplaza una prueba», dice Vidal. «Pero podés decidir qué hacemos con él».', [option('confess-force', 'Lo empujé. Estaba tratando de salir.', 'injury', [say('force', true), flag('admittedForce')]), option('deny-force', 'No lo toqué.', 'injury', [say('force', false)]), option('hide-force', 'Todavía no voy a hablar de eso.', 'alibi')], { onEnter: [remember('force', true, 'Empujaste a Sanz cuando avanzó con algo en la mano. Cayó contra el escritorio.'), feel(0, 18)], speaker: 'Tu recuerdo', kind: 'memory' }),
    scene('injury', 'V · Lo que falta en la escena', '04:03', 'Vidal mira la foto del corte, no tu brazo.\n«Esto es compatible con una defensa. Compatible no significa probado. Falta lo que pudo producirlo. Pilar vio a Marta salir con una bolsa. Podemos seguir ese dato o seguir preguntándote a vos».', [option('find-knife', 'Pedir que busquen la bolsa de Marta.', 'lost-property'), option('my-force', 'Yo lo empujé. Quiero que quede registrado.', 'decision', [say('force', true), flag('admittedForce')]), option('alibi-check', 'Antes, revisar lo que Marta me dio.', 'alibi')], { onEnter: [proof('injury')], presentation: { forensic: { reply: 'El impacto y tu lesión encajan con un forcejeo. Si existe un arma, necesitamos encontrarla.', effects: [flag('askedWeapon')] } } }),
    scene('lost-property', 'V · Lo que falta en la escena', '04:16', 'En objetos perdidos encontraron una toalla. Dentro, un cuchillo. El mango tiene huellas de Sanz; el filo, sangre tuya.\nVidal deja de mover la lapicera. «Marta intentó limpiar una escena. Eso no nos obliga a repetir su decisión».', [option('defense', 'Él tenía el cuchillo. Yo lo empujé para salir.', 'decision', [say('weapon', 'victim'), say('force', true), flag('admittedForce')]), option('only-proof', 'Incorporar la prueba sin declarar sobre el empujón.', 'decision'), option('ask-marta', 'Quiero entender qué pretendía Marta.', 'alibi')], { onEnter: [proof('knife')], kind: 'revelation' }),
    scene('alibi', 'V · Lo que falta en la escena', '04:22', 'El registro que Marta imprimió dice que saliste a las 22:40. El archivo fue creado media hora después. Detrás escribió: «Esto nos sirve a los dos».\nPor un instante, la hoja se parece a una puerta abierta. Sabés exactamente qué habría del otro lado.', [option('reject', 'Entregar la hoja y señalar que es falsa.', 'injury', [proof('alibi'), flag('rejectedAlibi')]), option('keep', 'Guardar la hoja y sostener esa salida.', 'decision', [proof('alibi', 'player'), flag('pact')]), option('truth', 'Dejar de buscar una salida: contar el empujón.', 'decision', [say('force', true), flag('admittedForce')])], { kind: 'decision' }),
    scene('decision', 'VI · La puerta que elegís', '04:31', '«Entraste, subiste y estuviste con Sanz. Lo demás necesita una versión que pueda examinarse. No una que simplemente te resulte cómoda».\nVidal da vuelta el acta. Esta cara de la hoja está en blanco.', [
      { ...option('formal-defense', 'Declarar el forcejeo y pedir que se cotejen todas las pruebas.', 'closing', [flag('decision', 'defense')]), when: { all: [{ flag: 'admittedForce', eq: true }, { evidence: 'knife' }, { flag: 'aligned', eq: true }] } },
      { ...option('pact-final', 'Sostener con Marta que salí antes de la muerte.', 'closing', [flag('decision', 'pact')]), when: { flag: 'pact', eq: true } },
      option('confess', 'Asumir la muerte y firmar sin pedir otra reconstrucción.', 'closing', [say('force', true), flag('decision', 'confess')]),
      option('investigate', 'Todavía falta buscar el arma.', 'lost-property'),
      option('clock-again', 'Revisar una vez más el orden de los horarios.', 'synchronize'),
      option('leave', 'No voy a añadir nada más a esta declaración.', 'closing', [flag('decision', 'leave')])
    ], { kind: 'decision', presentation: { 'clock-report': { reply: 'Queda asentada la corrección del reloj. No estabas en dos lugares a la vez.', effects: [flag('aligned')] }, knife: { reply: 'La prueba documenta una agresión previa de Sanz. Todavía necesito tu versión del forcejeo.', effects: [flag('weaponPresented')] } } }),
    scene('closing', 'VI · La puerta que elegís', '04:39', 'Detrás del vidrio se enciende una luz. Vidal junta los dos relojes que trajo a la mesa.\n«Uno puede mentir con un hecho verdadero. Basta con ponerle la hora equivocada».\nPor fin dejás de oír el ascensor.', [option('finish', 'Cerrar la declaración.', '$ending')], { kind: 'revelation' })
  ],
  endings: [
    { id: 'defensa', title: 'El minuto que faltaba', subtitle: 'FORCEJEO RECONSTRUIDO · DEFENSA DOCUMENTADA', when: { all: [{ flag: 'decision', eq: 'defense' }, { evidence: 'knife' }, { flag: 'aligned', eq: true }, { flag: 'admittedForce', eq: true }] }, text: 'Tu declaración no devuelve a Sanz a la vida. Sí permite ordenar lo que pasó antes de su caída: la amenaza, el cuchillo, la salida bloqueada. El expediente incorpora una reconstrucción compatible con tu defensa y deja de buscar un segundo Nicolás en los pasillos. Mientras continúa la investigación, el hotel retira el espejo junto al ascensor. Vos sabés que el espejo nunca fue el problema.', consequence: 'Combinaste la cronología corregida, el arma recuperada y el reconocimiento del empujón. Ninguna de esas piezas bastaba por separado.', reveals: ['Sanz murió cuando lo empujaste para salir de la habitación.', 'Marta escondió el cuchillo y ofreció una coartada falsa.', 'La simultaneidad aparente se debía al reloj de la cámara.'] },
    { id: 'pacto', title: 'No molestar', subtitle: 'COARTADA FALSA · SILENCIO COMPARTIDO', when: { flag: 'decision', eq: 'pact' }, text: 'La hoja de Marta entra en tu versión a pesar de que conocés su fecha de creación. Vidal no la acepta como prueba suficiente; te deja ir con la investigación abierta y una citación. Esa noche, Marta llama. No pregunta si estás bien. Pregunta si recordás lo que acordaron. Sanz ya no puede extorsionarte. Alguien aprendió su lugar.', consequence: 'Elegiste sostener una coartada que sabías fabricada. Tu libertad quedó atada al silencio de Marta.', reveals: ['La supuesta salida de las 22:40 fue inventada por Marta.'] },
    { id: 'detencion', title: 'Una firma sin contexto', subtitle: 'MUERTE RECONOCIDA · CUSTODIA', when: { flag: 'decision', eq: 'confess' }, text: 'Firmás que tu empujón causó la muerte. Vidal recibe el acta y ordena continuar las pericias; la reconstrucción de la agresión previa todavía no integra tu declaración formal. Te llevan a una sala de custodia mientras se determina lo ocurrido. En la pared hay un reloj detenido a las 22:58. Esta vez no necesitás que nadie lo corrija.', consequence: 'Asumiste la muerte sin sostener la reconstrucción de la defensa. La custodia surge de esa declaración, no de un contador de sospecha.', reveals: ['Tu empujón produjo el impacto fatal.'] },
    { id: 'umbral', title: 'Del lado de afuera', subtitle: 'SIN RECONSTRUCCIÓN COMPLETA', text: 'Vidal no tiene una prueba suficiente para atribuirte por sí sola el impacto. Salís con una citación, el brazo vendado y la llave que te devolvieron. El hotel cambia el número de la habitación. Durante semanas, cada puerta que abrís suena como aquella. Tu versión quedó incompleta; lo sucedido no.', consequence: 'No aportaste una declaración que uniera tu participación con las pruebas del forcejeo. La investigación sigue abierta.', reveals: [] }
  ]
};
